//! Translatable view emission for `autumn generate scaffold --i18n` (issue #1349).
//!
//! Autumn already ships the whole Fluent stack — the [`t!`] macro with
//! compile-time key validation, `Locale::t()`, the `i18n/<tag>.ftl` convention,
//! fallback chains, and an `Accept-Language` `Locale` extractor. What the
//! scaffold generator lacked was the wiring: every generated view emitted
//! hardcoded English, so localizing a resource meant hand-ripping the English
//! out of four views and hand-authoring the matching `.ftl` keys.
//!
//! [`ViewLabels`] is the single seam that closes that gap. Every user-facing
//! string in the generated views goes through it, and it emits one of two
//! things:
//!
//! * **`--i18n` off** — the caller's `plain` expression, returned *verbatim*.
//!   Byte-for-byte identity with the pre-#1349 scaffold is therefore structural,
//!   not a property some test has to keep re-checking: with the flag off this
//!   type is a `str -> str` identity function.
//! * **`--i18n` on** — a `t!(locale, "key")` lookup, and the key/English pair is
//!   recorded so [`merge_en_ftl`] can back-fill `i18n/en.ftl` with exactly the
//!   keys the views reference. That matters beyond tidiness: `t!` validates key
//!   existence *at compile time*, so a key the generator references but does not
//!   define is a `compile_error!` in the user's app, not a runtime miss.
//!
//! Because the English value written to `en.ftl` and the English rendered by the
//! non-i18n scaffold come from the same call site, an `en` app renders
//! identically either way (AC4) — there is no second copy of the strings to
//! drift.
//!
//! [`t!`]: autumn_web::t

use std::cell::RefCell;
use std::collections::BTreeMap;

use super::scaffold::{is_raw_string_start, skip_raw_string};

/// The comment introducing the shared-chrome block in a generated `en.ftl`.
const COMMON_HEADER: &str = "# Shared chrome — reused by every scaffolded resource.";

/// Prefix of the comment introducing one resource's block in a generated
/// `en.ftl`. The resource's `PascalCase` name and a trailing marker follow, so
/// `autumn destroy scaffold` can find and remove exactly the block it added.
const RESOURCE_HEADER_PREFIX: &str = "# ";

/// Trailer stamped on a generated resource block's comment so the destroy path
/// can identify it without guessing.
const RESOURCE_HEADER_SUFFIX: &str = " — generated by `autumn generate scaffold --i18n`.";

/// Emits every user-facing string in a generated view, either as the literal
/// English expression the plain scaffold uses or as a `t!(locale, "key")`
/// lookup.
///
/// See the [module docs](self) for why the `plain` expression is threaded
/// through rather than reconstructed.
#[derive(Debug)]
pub(super) struct ViewLabels {
    /// Whether `--i18n` is on. `false` makes every emitter method an identity
    /// function over its `plain` argument.
    enabled: bool,
    /// Keys actually referenced, mapped to the English value that must appear in
    /// `i18n/en.ftl`. Interior mutability so the emitters stay `&self` and can be
    /// threaded through the generator's `fn(&…) -> String` render helpers.
    used: RefCell<BTreeMap<String, String>>,
}

impl ViewLabels {
    /// A disabled emitter — every method returns its `plain` argument verbatim.
    pub(super) const fn disabled() -> Self {
        Self {
            enabled: false,
            used: RefCell::new(BTreeMap::new()),
        }
    }

    /// An emitter that translates. `enabled` is the `--i18n` flag, threaded
    /// rather than assumed so callers can build one emitter unconditionally.
    pub(super) const fn new(enabled: bool) -> Self {
        Self {
            enabled,
            used: RefCell::new(BTreeMap::new()),
        }
    }

    /// Whether this emitter translates.
    pub(super) const fn enabled(&self) -> bool {
        self.enabled
    }

    /// The key -> English map for every key the views actually referenced.
    ///
    /// Exactly this set is written to `en.ftl`: a key the generator never
    /// emitted would show up as "unused" under `autumn i18n check` (#1252), and
    /// a key it emitted but never defined would fail the user's build.
    pub(super) fn used_keys(&self) -> BTreeMap<String, String> {
        self.used.borrow().clone()
    }

    /// Record `key = ftl` and return the `t!` invocation for it.
    fn record(&self, key: &str, ftl: &str, args: &[(&str, &str)]) -> String {
        self.used
            .borrow_mut()
            .insert(key.to_owned(), ftl.to_owned());
        if args.is_empty() {
            format!("t!(locale, \"{key}\")")
        } else {
            let rendered: Vec<String> = args
                .iter()
                .map(|(name, expr)| format!("{name} = {expr}"))
                .collect();
            format!("t!(locale, \"{key}\", {})", rendered.join(", "))
        }
    }

    /// A string-valued site (`impl Into<String>` parameters such as
    /// `a11y::Link::new`/`Button::new`, `FormFor::override_label`, and Maud
    /// splice positions). `english` is the bare text; with `--i18n` off it is
    /// emitted as a quoted Rust literal, exactly as before.
    pub(super) fn lit(&self, key: &str, english: &str) -> String {
        if self.enabled {
            self.record(key, english, &[])
        } else {
            format!("\"{english}\"")
        }
    }

    /// [`Self::lit`] for a `&str` parameter (`layout(title)`,
    /// `widgets::Column::new`, `property_list` labels).
    pub(super) fn lit_ref(&self, key: &str, english: &str) -> String {
        if self.enabled {
            format!("&{}", self.record(key, english, &[]))
        } else {
            format!("\"{english}\"")
        }
    }

    /// [`Self::lit`] in Maud **body** position, where a bare literal renders as
    /// text but any expression must be parenthesised: `"Save"` becomes
    /// `(t!(locale, "common.save"))`.
    pub(super) fn markup(&self, key: &str, english: &str) -> String {
        if self.enabled {
            format!("({})", self.record(key, english, &[]))
        } else {
            format!("\"{english}\"")
        }
    }

    /// [`Self::expr`] in Maud body position.
    pub(super) fn markup_expr(
        &self,
        key: &str,
        ftl: &str,
        plain: &str,
        args: &[(&str, &str)],
    ) -> String {
        if self.enabled {
            format!("({})", self.record(key, ftl, args))
        } else {
            plain.to_owned()
        }
    }

    /// The general form: `plain` is the **complete** Rust expression the
    /// non-i18n scaffold emits (often a `format!(…)` call), `ftl` the Fluent
    /// value — which may carry `{ $arg }` placeholders fed by `args`, each a
    /// `(fluent name, Rust expression)` pair.
    pub(super) fn expr(&self, key: &str, ftl: &str, plain: &str, args: &[(&str, &str)]) -> String {
        if self.enabled {
            self.record(key, ftl, args)
        } else {
            plain.to_owned()
        }
    }

    /// [`Self::expr`] for a `&str` parameter.
    pub(super) fn expr_ref(
        &self,
        key: &str,
        ftl: &str,
        plain: &str,
        args: &[(&str, &str)],
    ) -> String {
        if self.enabled {
            format!("&{}", self.record(key, ftl, args))
        } else {
            plain.to_owned()
        }
    }
}

/// Split a `.ftl` source into its defined keys.
///
/// Mirrors the minimal parser in `autumn-macros`' `t!` validation and
/// `autumn-web`'s `Bundle` loader: a top-level `key = value` line, with `#`
/// comments and indented continuation lines skipped.
fn defined_keys(src: &str) -> BTreeMap<String, String> {
    src.lines()
        .filter(|line| {
            !line.trim_start().starts_with('#')
                && !line.trim().is_empty()
                && !line.starts_with(' ')
                && !line.starts_with('\t')
        })
        .filter_map(|line| line.split_once('='))
        .map(|(k, v)| (k.trim().to_owned(), v.trim().to_owned()))
        .collect()
}

/// Merge the keys a `--i18n` scaffold referenced into `existing` (the project's
/// `i18n/en.ftl`, or `""` when there is none yet).
///
/// Semantics, in order of importance:
///
/// 1. **A key that already exists is never rewritten.** Re-running the
///    generator over a file whose English has been edited — or whose keys a
///    translator has already worked from — must not clobber it.
/// 2. **Shared chrome is written once.** `common.*` keys land in one block that
///    later resources add to rather than duplicate (AC5).
/// 3. **The resource's own keys are grouped** under a marked comment, so a
///    translator reads the file by resource and `autumn destroy scaffold` can
///    remove exactly what this generator added.
///
/// Returns `existing` unchanged when every key is already defined, so the
/// generator can skip the write and leave the file out of the plan.
pub(super) fn merge_en_ftl(
    existing: &str,
    pascal_name: &str,
    resource: &str,
    keys: &BTreeMap<String, String>,
) -> String {
    use std::fmt::Write as _;

    let already = defined_keys(existing);
    let resource_prefix = format!("{resource}.");
    // A resource literally named `Common` would share its prefix with the chrome
    // block. `plan_scaffold_with_options_impl` refuses that name under `--i18n`;
    // classifying chrome FIRST and taking the resource's keys from what is left
    // is the belt-and-braces half, so no key can ever be written to both blocks
    // even from a hand-built plan.
    let missing_common: Vec<(&String, &String)> = keys
        .iter()
        .filter(|(k, _)| k.starts_with("common.") && !already.contains_key(*k))
        .collect();
    let missing_resource: Vec<(&String, &String)> = keys
        .iter()
        .filter(|(k, _)| {
            k.starts_with(&resource_prefix)
                && !k.starts_with("common.")
                && !already.contains_key(*k)
        })
        .collect();
    if missing_common.is_empty() && missing_resource.is_empty() {
        return existing.to_owned();
    }

    let resource_header = format!("{RESOURCE_HEADER_PREFIX}{pascal_name}{RESOURCE_HEADER_SUFFIX}");
    // Re-running the generator — after adding a column, or with a flag that
    // brings new chrome — must extend the block that already exists rather than
    // strand the new key at EOF under no header at all. The file's whole promise
    // to a translator is that it reads by section, and `destroy` finds a
    // resource's keys by prefix, not by position.
    //
    // Insert into the LATER block first: an edit shifts every offset after it,
    // and the resource block always follows the chrome block.
    for (block_header, missing) in [
        (resource_header.as_str(), &missing_resource),
        (COMMON_HEADER, &missing_common),
    ] {
        if missing.is_empty() {
            continue;
        }
        let Some(insert_at) = block_end(existing, block_header) else {
            continue;
        };
        let mut out = String::with_capacity(existing.len() + missing.len() * 48);
        out.push_str(&existing[..insert_at]);
        for (key, value) in missing {
            let _ = writeln!(out, "{key} = {value}");
        }
        out.push_str(&existing[insert_at..]);
        // Whatever the other block still needs lands on the next pass, which
        // terminates: this block's keys are now all present.
        return merge_en_ftl(&out, pascal_name, resource, keys);
    }

    let mut out = String::with_capacity(existing.len() + (keys.len() + 4) * 48);
    if existing.is_empty() {
        out.push_str(
            "# Generated by `autumn generate scaffold --i18n`.\n\
             #\n\
             # This is the DEFAULT locale — leave these values in their own language.\n\
             # To add a locale, copy this file to `i18n/<tag>.ftl` and translate THERE.\n\
             # Keys are grouped by resource; `common.*` is shared chrome every\n\
             # scaffolded resource reuses.\n\n",
        );
    } else {
        out.push_str(existing);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }

    if !missing_common.is_empty() {
        out.push_str(COMMON_HEADER);
        out.push('\n');
        for (key, value) in missing_common {
            let _ = writeln!(out, "{key} = {value}");
        }
        if !missing_resource.is_empty() {
            out.push('\n');
        }
    }
    if !missing_resource.is_empty() {
        if !existing.contains(&resource_header) {
            out.push_str(&resource_header);
            out.push('\n');
        }
        for (key, value) in missing_resource {
            let _ = writeln!(out, "{key} = {value}");
        }
    }
    out
}

/// Byte offset just past the last key line of the block `header` introduces, or
/// `None` when `existing` carries no such block. Used for both the shared
/// chrome block and a resource's own.
///
/// The block runs from its header to the first blank line or foreign comment —
/// the same shape [`merge_en_ftl`] writes.
fn block_end(existing: &str, header: &str) -> Option<usize> {
    let start = existing.find(header)?;
    let mut cursor = start + header.len();
    // Step past the header's own newline.
    cursor += existing[cursor..].find('\n').map_or(0, |i| i + 1);
    let mut end = cursor;
    for line in existing[cursor..].split_inclusive('\n') {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            break;
        }
        end += line.len();
    }
    Some(end)
}

/// Inverse of [`merge_en_ftl`] for `autumn destroy scaffold` — remove one
/// resource's block (its marked comment plus every `<resource>.` key) from
/// `existing`.
///
/// The shared `common.*` block is deliberately left alone: other scaffolded
/// resources reuse it, and it is what keeps the file non-empty. That matters —
/// the generated app calls `.i18n_auto()`, which panics at startup if the
/// default locale's file is missing, so destroy must never empty or delete it.
pub(super) fn remove_en_ftl_keys(existing: &str, pascal_name: &str, resource: &str) -> String {
    let stripped = remove_resource_block(existing, pascal_name, resource);
    // Chrome exists to be shared. Once the last generated resource block is
    // gone, every `common.*` key is referenced by nothing — which is exactly
    // what `autumn i18n check --strict` fails on, so destroying the only
    // `--i18n` resource would leave the project's own lint red. Take the chrome
    // with it, but never the FILE: `.i18n_auto()` panics at startup when the
    // default locale's bundle is missing, and a comment-only bundle still loads.
    if stripped.contains(RESOURCE_HEADER_SUFFIX) {
        return stripped;
    }
    remove_chrome_block(&stripped)
}

/// Remove every `common.*` key (and the chrome header) written by this
/// generator, leaving any hand-authored key untouched.
fn remove_chrome_block(existing: &str) -> String {
    let mut out: Vec<&str> = Vec::with_capacity(existing.lines().count());
    let mut dropping_continuations = false;
    for line in existing.lines() {
        let indented = line.starts_with(' ') || line.starts_with('\t');
        if indented {
            if dropping_continuations {
                continue;
            }
            out.push(line);
            continue;
        }
        dropping_continuations = false;
        if line.trim_end() == COMMON_HEADER {
            continue;
        }
        if line
            .split_once('=')
            .is_some_and(|(k, _)| k.trim().starts_with("common."))
        {
            dropping_continuations = true;
            continue;
        }
        out.push(line);
    }
    collapse_blank_runs(&out)
}

fn remove_resource_block(existing: &str, pascal_name: &str, resource: &str) -> String {
    let header = format!("{RESOURCE_HEADER_PREFIX}{pascal_name}{RESOURCE_HEADER_SUFFIX}");
    let prefix = format!("{resource}.");
    let mut out: Vec<&str> = Vec::with_capacity(existing.lines().count());
    // A Fluent value may continue over following INDENTED lines. Dropping the
    // `key =` line alone would leave those orphaned, which the loader either
    // rejects outright ("indented continuation has no preceding key" — and
    // `.i18n_auto()` turns that into a startup panic) or silently glues onto
    // whichever key precedes them, corrupting a translation that has nothing to
    // do with the destroyed resource. So a removed key takes its continuation
    // lines with it.
    let mut dropping_continuations = false;
    for line in existing.lines() {
        let indented = line.starts_with(' ') || line.starts_with('\t');
        if indented {
            if dropping_continuations {
                continue;
            }
            out.push(line);
            continue;
        }
        dropping_continuations = false;
        if line.trim_end() == header {
            continue;
        }
        // Only top-level `key = value` lines define keys.
        let is_resource_key = line
            .split_once('=')
            .is_some_and(|(k, _)| k.trim().starts_with(&prefix));
        if is_resource_key {
            dropping_continuations = true;
            continue;
        }
        out.push(line);
    }
    collapse_blank_runs(&out)
}

/// Re-join `lines`, collapsing the blank runs a removed block leaves behind and
/// restoring the file's single trailing newline.
fn collapse_blank_runs(lines: &[&str]) -> String {
    let mut joined = String::with_capacity(lines.iter().map(|l| l.len() + 1).sum());
    let mut prev_blank = false;
    for line in lines {
        let blank = line.trim().is_empty();
        if blank && prev_blank {
            continue;
        }
        prev_blank = blank;
        joined.push_str(line);
        joined.push('\n');
    }
    while joined.ends_with("\n\n") {
        joined.pop();
    }
    joined
}

/// The `default_locale` an existing `autumn.toml` configures, if any.
///
/// The generated keys have to land in the bundle the app actually resolves
/// through. A project on `default_locale = "fr"` looks up every key in
/// `fr.ftl` first and falls back down its configured chain — which need not
/// include `en` — so keys written to `en.ftl` would render as visible
/// `{$key}` placeholders and read as missing to `autumn i18n check`.
///
/// Deliberately a line scan rather than a TOML parse: this only needs the one
/// key, the file may carry profile overlays the generator has no business
/// interpreting, and a malformed `autumn.toml` should not fail generation here
/// (the app's own loader reports that far better). Returns `None` when there is
/// no `[i18n]` section or it names no default, so the caller falls back to `en`.
pub(super) fn configured_default_locale(autumn_toml: &str) -> Option<String> {
    let mut in_i18n = false;
    for line in autumn_toml.lines() {
        let trimmed = line.trim();
        if let Some(name) = trimmed
            .strip_prefix('[')
            .and_then(|rest| rest.strip_suffix(']'))
        {
            // `[profile.prod.i18n]` overlays are deliberately ignored: the
            // generator writes the base bundle, which every profile inherits.
            in_i18n = name.trim() == "i18n";
            continue;
        }
        if !in_i18n {
            continue;
        }
        if let Some(value) = trimmed.strip_prefix("default_locale") {
            let value = value.trim_start().strip_prefix('=')?.trim();
            let tag = value.trim_matches(|c| c == '"' || c == '\'');
            if !tag.is_empty() {
                return Some(tag.to_owned());
            }
        }
    }
    None
}

/// Ship the `i18n/` sidecar into a generated `Dockerfile`, in both stages.
///
/// `.i18n_auto()` reads `i18n/<default>.ftl` from the working directory at
/// startup and **panics** when it is missing (`autumn/src/app.rs`'s
/// `resolve_i18n_bundle`). `autumn new --with-i18n` handles this by resolving
/// the Dockerfile's i18n anchors; a plain `autumn new` strips them, so a project
/// that adopts `--i18n` later builds an image with no bundle in it and
/// crash-loops on deploy — after a build that looked completely clean, because
/// `t!`'s compile-time key check silently degrades to a runtime lookup when the
/// file is absent from the build context.
///
/// The two `COPY` lines are inserted next to the ones for `migrations/`, which
/// both stages already carry and which sit at exactly the same layer. Returns
/// `None` when the file has no such anchor (a hand-edited or absent Dockerfile),
/// so the caller can warn instead of guessing where to write.
pub(super) fn ensure_dockerfile_i18n_copy(dockerfile: &str, dir: &str) -> Option<String> {
    let builder_anchor = "COPY migrations ./migrations";
    let runtime_anchor = "COPY --from=builder /app/migrations /app/migrations";
    let builder_line = format!("COPY {dir} ./{dir}");
    let runtime_line = format!("COPY --from=builder /app/{dir} /app/{dir}");
    if dockerfile.contains(&builder_line) && dockerfile.contains(&runtime_line) {
        return Some(dockerfile.to_owned());
    }
    if !dockerfile.contains(builder_anchor) || !dockerfile.contains(runtime_anchor) {
        return None;
    }
    // Runtime stage first: its anchor is a superstring-free, later occurrence,
    // and replacing the builder anchor first would shift it.
    let out = dockerfile.replacen(
        runtime_anchor,
        &format!("{runtime_anchor}\n{runtime_line}"),
        1,
    );
    Some(out.replacen(
        builder_anchor,
        &format!("{builder_anchor}\n{builder_line}"),
        1,
    ))
}

/// Add an `[i18n]` block to `autumn.toml` if it has none.
///
/// `default_locale = "en"` matches the `en.ftl` the generator writes; the
/// supported list starts as `["en"]` so an app that adds `fr.ftl` only has to
/// extend one line. A project that already configures `[i18n]` is left alone —
/// its `default_locale` may not be `en`, and rewriting it would silently
/// repoint the bundle the app loads.
pub(super) fn ensure_i18n_config_block(existing: &str) -> String {
    // Match the SECTION, not the literal text: `[ i18n ]` is legal TOML, and
    // appending a second `[i18n]` beside it makes the whole file unparseable
    // ("cannot declare i18n twice"), taking the app's config down with it.
    let already_configured = existing.lines().any(|line| {
        let t = line.trim();
        t.strip_prefix('[')
            .and_then(|rest| rest.strip_suffix(']'))
            .is_some_and(|name| name.trim() == "i18n")
    });
    if already_configured {
        return existing.to_owned();
    }
    let mut out = existing.to_owned();
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out.push_str("[i18n]\ndefault_locale = \"en\"\nsupported_locales = [\"en\"]\n");
    out
}

/// Byte offsets of every `needle` in `src` that is REAL CODE — not inside a
/// line comment, a (nestable) block comment, a string or raw-string literal, or
/// a char literal.
///
/// `autumn new`'s own template carries the line
/// `// Register new endpoints by adding them to the .routes(routes![...]) list`
/// right above `fn main`, and a naive `find(".routes(")` lands there: the
/// `.i18n_auto()` call gets written into a COMMENT, the builder chain is never
/// touched, and the idempotency guard then makes every later run a no-op. The
/// app compiles, starts, and renders raw keys forever with no error anywhere.
/// Same class of decoy — and the same lexical defence — as
/// [`has_shared_layout`](super::scaffold::has_shared_layout).
fn real_offsets(src: &str, needle: &str) -> Vec<usize> {
    let bytes = src.as_bytes();
    let n = needle.as_bytes();
    let mut out = Vec::new();
    let mut i = 0usize;
    let mut block_depth = 0usize;
    while i < bytes.len() {
        if block_depth > 0 {
            if bytes[i..].starts_with(b"/*") {
                block_depth += 1;
                i += 2;
            } else if bytes[i..].starts_with(b"*/") {
                block_depth -= 1;
                i += 2;
            } else {
                i += 1;
            }
            continue;
        }
        if bytes[i..].starts_with(b"//") {
            i += src[i..].find('\n').map_or(src.len() - i, |nl| nl + 1);
            continue;
        }
        if bytes[i..].starts_with(b"/*") {
            block_depth = 1;
            i += 2;
            continue;
        }
        if is_raw_string_start(bytes, i) {
            i = skip_raw_string(bytes, i);
            continue;
        }
        if bytes[i] == b'"' {
            i += 1;
            while i < bytes.len() && bytes[i] != b'"' {
                i += usize::from(bytes[i] == b'\\') + 1;
            }
            i += 1;
            continue;
        }
        if bytes[i..].starts_with(n) {
            out.push(i);
            i += n.len();
            continue;
        }
        i += 1;
    }
    out
}

/// Whether the app builder in `main_rs` already installs an i18n bundle.
///
/// Checked lexically for the same reason the anchor is: an `.i18n_auto()`
/// mentioned only in a doc comment must not make the wiring a silent no-op.
fn installs_i18n_bundle(main_rs: &str) -> bool {
    !real_offsets(main_rs, ".i18n_auto()").is_empty() || !real_offsets(main_rs, ".i18n(").is_empty()
}

/// The outcome of trying to wire `.i18n_auto()` into `main.rs`.
#[derive(Debug, PartialEq, Eq)]
pub(super) enum I18nAutoWiring {
    /// The builder chain now calls `.i18n_auto()` (or already did).
    Wired(String),
    /// No real `.routes(` call was found, so there is nowhere safe to insert.
    /// The caller surfaces this as a plan warning rather than writing the call
    /// into a comment, where it would silently never run.
    NoAnchor,
}

/// Insert `.i18n_auto()` into the `AppBuilder` chain in `main.rs` so the
/// generated `t!` lookups actually resolve (AC4's "zero further config").
///
/// Inserted immediately before the first REAL `.routes(` call — the same anchor
/// `autumn new --with-i18n` uses, but found with a comment/string-aware scan
/// (see [`real_routes_call_offsets`]). A `main.rs` that already installs a
/// bundle — `.i18n_auto()` or an explicit `.i18n(...)` — is left untouched: an
/// app that built its own `Bundle` from embedded files or a
/// translation-management service must not have it swapped for a filesystem
/// load.
pub(super) fn ensure_i18n_auto(main_rs: &str) -> I18nAutoWiring {
    if installs_i18n_bundle(main_rs) {
        return I18nAutoWiring::Wired(main_rs.to_owned());
    }
    let Some(&anchor) = real_offsets(main_rs, ".routes(").first() else {
        return I18nAutoWiring::NoAnchor;
    };
    // Reuse the anchor line's own indentation so the inserted call sits in the
    // builder chain rather than at some arbitrary column.
    let line_start = main_rs[..anchor].rfind('\n').map_or(0, |i| i + 1);
    if !main_rs[line_start..anchor].trim_start().is_empty() {
        // `.routes(` is not the first token on its line (e.g. a single-line
        // builder chain). Insert inline, which is still valid Rust.
        return I18nAutoWiring::Wired(format!(
            "{}.i18n_auto(){}",
            &main_rs[..anchor],
            &main_rs[anchor..]
        ));
    }
    let indent: String = main_rs[line_start..anchor]
        .chars()
        .take_while(|c| c.is_whitespace())
        .collect();
    I18nAutoWiring::Wired(format!(
        "{}{indent}.i18n_auto()\n{}",
        &main_rs[..line_start],
        &main_rs[line_start..]
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn keys(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
            .collect()
    }

    #[test]
    fn disabled_emitter_is_an_identity_over_the_plain_expression() {
        let labels = ViewLabels::disabled();
        assert_eq!(labels.lit("common.create", "Create"), "\"Create\"");
        assert_eq!(
            labels.lit_ref("post.index.title", "Post index"),
            "\"Post index\""
        );
        assert_eq!(
            labels.expr(
                "post.show.title",
                "Post #{ $id }",
                "&format!(\"Post #{}\", id)",
                &[]
            ),
            "&format!(\"Post #{}\", id)"
        );
        assert!(labels.used_keys().is_empty());
    }

    #[test]
    fn enabled_emitter_records_keys_and_emits_lookups() {
        let labels = ViewLabels::new(true);
        assert_eq!(
            labels.lit("common.create", "Create"),
            "t!(locale, \"common.create\")"
        );
        assert_eq!(
            labels.lit_ref("post.index.title", "Post index"),
            "&t!(locale, \"post.index.title\")"
        );
        assert_eq!(
            labels.expr(
                "common.new",
                "New { $resource }",
                "\"New Post\"",
                &[("resource", "&l_resource")]
            ),
            "t!(locale, \"common.new\", resource = &l_resource)"
        );
        let used = labels.used_keys();
        assert_eq!(used.get("common.create").unwrap(), "Create");
        assert_eq!(used.get("common.new").unwrap(), "New { $resource }");
    }

    #[test]
    fn merge_writes_a_header_and_both_blocks_into_an_empty_file() {
        let out = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.name", "Post")]),
        );
        assert!(out.contains(COMMON_HEADER), "{out}");
        assert!(out.contains("common.create = Create"), "{out}");
        assert!(out.contains("post.name = Post"), "{out}");
        assert!(out.contains("Post — generated by"), "{out}");
    }

    #[test]
    fn merge_never_rewrites_an_existing_value() {
        let existing = "common.create = Add\n";
        let out = merge_en_ftl(
            existing,
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.name", "Post")]),
        );
        assert!(out.contains("common.create = Add"), "{out}");
        assert!(!out.contains("common.create = Create"), "{out}");
        assert!(out.contains("post.name = Post"), "{out}");
    }

    #[test]
    fn merge_is_idempotent() {
        let pairs = keys(&[("common.create", "Create"), ("post.name", "Post")]);
        let once = merge_en_ftl("", "Post", "post", &pairs);
        let twice = merge_en_ftl(&once, "Post", "post", &pairs);
        assert_eq!(once, twice);
    }

    #[test]
    fn merge_shares_the_common_block_across_resources() {
        let first = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.name", "Post")]),
        );
        let second = merge_en_ftl(
            &first,
            "Comment",
            "comment",
            &keys(&[("common.create", "Create"), ("comment.name", "Comment")]),
        );
        assert_eq!(second.matches("common.create =").count(), 1, "{second}");
        assert_eq!(second.matches(COMMON_HEADER).count(), 1, "{second}");
        assert!(second.contains("comment.name = Comment"), "{second}");
        assert!(second.contains("post.name = Post"), "{second}");
    }

    #[test]
    fn remove_takes_only_the_resource_block() {
        // A sibling resource keeps the shared chrome in use, so only `Post`'s
        // own block comes out. (Destroying the LAST resource takes the chrome
        // too — see `removing_the_last_resource_takes_the_now_unreferenced_chrome_with_it`.)
        let ftl = merge_en_ftl(
            &merge_en_ftl(
                "",
                "Post",
                "post",
                &keys(&[("common.create", "Create"), ("post.name", "Post")]),
            ),
            "Comment",
            "comment",
            &keys(&[("common.create", "Create"), ("comment.name", "Comment")]),
        );
        let out = remove_en_ftl_keys(&ftl, "Post", "post");
        assert!(out.contains("common.create = Create"), "{out}");
        assert!(!out.contains("post.name"), "{out}");
        assert!(!out.contains("Post — generated by"), "{out}");
        assert!(out.contains("comment.name = Comment"), "{out}");
        // Idempotent: destroying twice is a no-op.
        assert_eq!(remove_en_ftl_keys(&out, "Post", "post"), out);
    }

    #[test]
    fn remove_leaves_a_sibling_resource_intact() {
        let ftl = merge_en_ftl(
            &merge_en_ftl("", "Post", "post", &keys(&[("post.name", "Post")])),
            "Comment",
            "comment",
            &keys(&[("comment.name", "Comment")]),
        );
        let out = remove_en_ftl_keys(&ftl, "Post", "post");
        assert!(out.contains("comment.name = Comment"), "{out}");
        assert!(!out.contains("post.name"), "{out}");
    }

    #[test]
    fn config_block_is_added_once() {
        let once = ensure_i18n_config_block("[server]\nport = 3000\n");
        assert!(once.contains("[i18n]"), "{once}");
        assert!(once.contains("default_locale = \"en\""), "{once}");
        assert_eq!(ensure_i18n_config_block(&once), once);
    }

    #[test]
    fn config_block_respects_an_existing_i18n_section() {
        let existing = "[i18n]\ndefault_locale = \"fr\"\n";
        assert_eq!(ensure_i18n_config_block(existing), existing);
    }

    #[test]
    fn i18n_auto_is_inserted_before_the_routes_call() {
        let main_rs = "fn main() {\n    autumn_web::app()\n        .routes(routes![index])\n        .run();\n}\n";
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected an anchor");
        };
        assert!(
            out.contains("        .i18n_auto()\n        .routes(routes![index])"),
            "{out}"
        );
        assert_eq!(
            ensure_i18n_auto(&out),
            I18nAutoWiring::Wired(out.clone()),
            "must be idempotent"
        );
    }

    #[test]
    fn i18n_auto_respects_a_hand_installed_bundle() {
        let main_rs = "fn main() {\n    autumn_web::app()\n        .i18n(my_bundle())\n        .routes(routes![index]);\n}\n";
        assert_eq!(
            ensure_i18n_auto(main_rs),
            I18nAutoWiring::Wired(main_rs.to_owned())
        );
    }

    /// `autumn new`'s own template mentions `.routes(routes![...])` in a comment
    /// above `fn main`. Anchoring there would write `.i18n_auto()` INTO that
    /// comment: the app compiles, starts, and renders raw keys forever, and the
    /// idempotency guard makes every later run a no-op.
    #[test]
    fn i18n_auto_ignores_a_routes_call_inside_a_comment() {
        let main_rs = concat!(
            "// Register new endpoints by adding them to the .routes(routes![...]) list.\n",
            "fn main() {\n",
            "    autumn_web::app()\n",
            "        .routes(routes![index])\n",
            "        .run();\n",
            "}\n",
        );
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected the real anchor to be found");
        };
        assert!(
            out.contains("        .i18n_auto()\n        .routes(routes![index])"),
            "must anchor on the real builder call:\n{out}"
        );
        assert!(
            out.lines().next().unwrap().ends_with("list."),
            "the comment must be left alone:\n{out}"
        );
    }

    /// A `.i18n_auto()` that appears only in a doc comment must not be mistaken
    /// for a bundle the app already installs.
    #[test]
    fn i18n_auto_ignores_a_mention_inside_a_doc_comment() {
        let main_rs = concat!(
            "/// Call `.i18n_auto()` to load translations.\n",
            "fn main() {\n",
            "    autumn_web::app()\n",
            "        .routes(routes![index]);\n",
            "}\n",
        );
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected an anchor");
        };
        assert!(
            out.contains("        .i18n_auto()\n        .routes(routes![index])"),
            "{out}"
        );
    }

    #[test]
    fn i18n_auto_reports_no_anchor_rather_than_guessing() {
        let main_rs = "fn main() {\n    println!(\"no builder here\");\n}\n";
        assert_eq!(ensure_i18n_auto(main_rs), I18nAutoWiring::NoAnchor);
    }

    #[test]
    fn config_block_detects_a_spaced_section_header() {
        // `[ i18n ]` is legal TOML; appending a second `[i18n]` beside it makes
        // the whole file unparseable and takes the app's config down with it.
        let existing = "[ i18n ]\ndefault_locale = \"fr\"\n";
        assert_eq!(ensure_i18n_config_block(existing), existing);
    }

    #[test]
    fn default_locale_is_read_from_the_config() {
        assert_eq!(
            configured_default_locale("[i18n]\ndefault_locale = \"fr\"\n").as_deref(),
            Some("fr")
        );
        assert_eq!(
            configured_default_locale("[ i18n ]\ndefault_locale = 'pt-BR'\n").as_deref(),
            Some("pt-BR")
        );
        // A `default_locale` under some OTHER section is not ours.
        assert_eq!(
            configured_default_locale("[server]\ndefault_locale = \"fr\"\n"),
            None
        );
        assert_eq!(configured_default_locale("[server]\nport = 3000\n"), None);
    }

    #[test]
    fn removal_takes_a_multi_line_value_with_its_key() {
        // A translator may wrap a value over indented continuation lines. Left
        // behind, they either fail the loader outright — and `.i18n_auto()`
        // turns that into a startup panic — or silently glue onto whichever key
        // precedes them, corrupting an unrelated translation.
        let ftl = concat!(
            "common.show = Show\n",
            "\n",
            "# Comment — generated by `autumn generate scaffold --i18n`.\n",
            "comment.new = New Comment\n",
            "\n",
            "# Post — generated by `autumn generate scaffold --i18n`.\n",
            "post.index.title = Post index\n",
            "    continued here\n",
            "post.new = New Post\n",
        );
        let out = remove_en_ftl_keys(ftl, "Post", "post");
        assert!(
            !out.contains("continued here"),
            "an orphaned continuation either fails the loader — and `.i18n_auto()` \
             turns that into a startup panic — or silently glues onto the key above \
             it:\n{out}"
        );
        assert!(!out.contains("post."), "{out}");
        // The sibling resource keeps the chrome alive.
        assert!(out.contains("common.show = Show"), "{out}");
        assert!(out.contains("comment.new = New Comment"), "{out}");
    }

    #[test]
    fn removing_the_last_resource_takes_the_now_unreferenced_chrome_with_it() {
        let ftl = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.new", "New Post")]),
        );
        let out = remove_en_ftl_keys(&ftl, "Post", "post");
        assert!(
            !out.contains("common.create"),
            "chrome nothing references any more fails `i18n check --strict`:\n{out}"
        );
        // …but a SIBLING resource keeps it alive.
        let two = merge_en_ftl(
            &ftl,
            "Comment",
            "comment",
            &keys(&[("common.create", "Create"), ("comment.new", "New Comment")]),
        );
        let still = remove_en_ftl_keys(&two, "Post", "post");
        assert!(still.contains("common.create = Create"), "{still}");
        assert!(still.contains("comment.new = New Comment"), "{still}");
    }

    #[test]
    fn a_regenerated_key_lands_inside_its_own_block() {
        let first = merge_en_ftl("", "Post", "post", &keys(&[("post.new", "New Post")]));
        let second = merge_en_ftl(
            &first,
            "Post",
            "post",
            &keys(&[("post.new", "New Post"), ("post.field.body", "Body")]),
        );
        let header_at = second.find("Post — generated by").expect("header");
        let key_at = second.find("post.field.body").expect("new key");
        assert!(
            key_at > header_at,
            "the new key must sit under the header:\n{second}"
        );
        // Nothing after the block but the trailing newline — i.e. it did not
        // land at EOF outside the block.
        assert!(
            second.trim_end().ends_with("Body") || second.contains("post.field.body = Body\npost."),
            "{second}"
        );
    }

    #[test]
    fn dockerfile_gains_the_bundle_in_both_stages() {
        let dockerfile = concat!(
            "FROM rust AS builder\n",
            "COPY migrations ./migrations\n",
            "\n",
            "FROM debian AS runtime\n",
            "COPY --from=builder /app/migrations /app/migrations\n",
        );
        let out = ensure_dockerfile_i18n_copy(dockerfile, "i18n").expect("anchors present");
        assert!(out.contains("COPY i18n ./i18n"), "{out}");
        assert!(
            out.contains("COPY --from=builder /app/i18n /app/i18n"),
            "{out}"
        );
        assert_eq!(
            ensure_dockerfile_i18n_copy(&out, "i18n").as_deref(),
            Some(out.as_str()),
            "must be idempotent"
        );
        // A Dockerfile with no anchor is reported, not guessed at.
        assert_eq!(ensure_dockerfile_i18n_copy("FROM scratch\n", "i18n"), None);
    }
}
