//! Translatable view emission for `autumn generate scaffold --i18n` (issue #1349).
//!
//! Autumn already ships the whole Fluent stack — the [`t!`] macro with
//! compile-time key validation, `Locale::t()`, the `i18n/<tag>.ftl` convention,
//! fallback chains, and an `Accept-Language` `Locale` extractor. What the
//! scaffold generator lacked was the wiring: every generated view emitted
//! hardcoded English, so localizing a resource meant hand-ripping the English
//! out of four views and hand-authoring the matching `.ftl` keys.
//!
//! [`ViewLabels`] is the single seam that closes that gap. Every user-facing
//! string in the generated views goes through it, and it emits one of two
//! things:
//!
//! * **`--i18n` off** — the caller's `plain` expression, returned *verbatim*.
//!   Byte-for-byte identity with the pre-#1349 scaffold is therefore structural,
//!   not a property some test has to keep re-checking: with the flag off this
//!   type is a `str -> str` identity function.
//! * **`--i18n` on** — a `t!(locale, "key")` lookup, and the key/English pair is
//!   recorded so [`merge_en_ftl`] can back-fill `i18n/en.ftl` with exactly the
//!   keys the views reference. That matters beyond tidiness: `t!` validates key
//!   existence *at compile time*, so a key the generator references but does not
//!   define is a `compile_error!` in the user's app, not a runtime miss.
//!
//! Because the English value written to `en.ftl` and the English rendered by the
//! non-i18n scaffold come from the same call site, an `en` app renders
//! identically either way (AC4) — there is no second copy of the strings to
//! drift.
//!
//! [`t!`]: autumn_web::t

use std::cell::RefCell;
use std::collections::BTreeMap;

use super::scaffold::{is_raw_string_start, skip_raw_string};

/// The comment introducing the shared-chrome block in a generated `en.ftl`.
const COMMON_HEADER: &str = "# Shared chrome — reused by every scaffolded resource.";

/// Prefix of the comment introducing one resource's block in a generated
/// `en.ftl`. The resource's `PascalCase` name and a trailing marker follow, so
/// `autumn destroy scaffold` can find and remove exactly the block it added.
const RESOURCE_HEADER_PREFIX: &str = "# ";

/// Trailer stamped on a generated resource block's comment so the destroy path
/// can identify it without guessing.
const RESOURCE_HEADER_SUFFIX: &str = " — generated by `autumn generate scaffold --i18n`.";

/// Closes the shared-chrome block.
const COMMON_FOOTER: &str = "# — end shared chrome —";

/// Closes a resource's block. The `PascalCase` name goes between the two
/// halves, mirroring its header.
const RESOURCE_FOOTER_PREFIX: &str = "# — end ";
const RESOURCE_FOOTER_SUFFIX: &str = " —";

/// The comment closing the block `header` opens.
///
/// Blocks are explicitly CLOSED rather than run to the first blank line or
/// comment, because a `.ftl` is a file people edit: a translator who groups
/// keys with a blank line, or leaves a `# careful, this one is on a button`
/// note beside one, would otherwise move the boundary. `destroy` would then
/// take the header and the keys above the separator and strand the rest — with
/// no call sites left, so `autumn i18n check --strict` starts failing on keys
/// nobody can find the owner of. An explicit marker lets formatting and
/// comments live inside the block while everything outside it stays the
/// application's own.
fn block_footer(header: &str) -> String {
    if header == COMMON_HEADER {
        return COMMON_FOOTER.to_owned();
    }
    let pascal = header
        .strip_prefix(RESOURCE_HEADER_PREFIX)
        .and_then(|rest| rest.strip_suffix(RESOURCE_HEADER_SUFFIX))
        .unwrap_or_default();
    format!("{RESOURCE_FOOTER_PREFIX}{pascal}{RESOURCE_FOOTER_SUFFIX}")
}

/// Emits every user-facing string in a generated view, either as the literal
/// English expression the plain scaffold uses or as a `t!(locale, "key")`
/// lookup.
///
/// See the [module docs](self) for why the `plain` expression is threaded
/// through rather than reconstructed.
#[derive(Debug)]
pub(super) struct ViewLabels {
    /// Whether `--i18n` is on. `false` makes every emitter method an identity
    /// function over its `plain` argument.
    enabled: bool,
    /// Keys actually referenced, mapped to the English value that must appear in
    /// `i18n/en.ftl`. Interior mutability so the emitters stay `&self` and can be
    /// threaded through the generator's `fn(&…) -> String` render helpers.
    used: RefCell<BTreeMap<String, String>>,
}

impl ViewLabels {
    /// A disabled emitter — every method returns its `plain` argument verbatim.
    pub(super) const fn disabled() -> Self {
        Self {
            enabled: false,
            used: RefCell::new(BTreeMap::new()),
        }
    }

    /// An emitter that translates. `enabled` is the `--i18n` flag, threaded
    /// rather than assumed so callers can build one emitter unconditionally.
    pub(super) const fn new(enabled: bool) -> Self {
        Self {
            enabled,
            used: RefCell::new(BTreeMap::new()),
        }
    }

    /// Whether this emitter translates.
    pub(super) const fn enabled(&self) -> bool {
        self.enabled
    }

    /// The key -> English map for every key the views actually referenced.
    ///
    /// Exactly this set is written to `en.ftl`: a key the generator never
    /// emitted would show up as "unused" under `autumn i18n check` (#1252), and
    /// a key it emitted but never defined would fail the user's build.
    pub(super) fn used_keys(&self) -> BTreeMap<String, String> {
        self.used.borrow().clone()
    }

    /// Record `key = ftl` and return the `t!` invocation for it.
    fn record(&self, key: &str, ftl: &str, args: &[(&str, &str)]) -> String {
        self.used
            .borrow_mut()
            .insert(key.to_owned(), ftl.to_owned());
        if args.is_empty() {
            format!("t!(locale, \"{key}\")")
        } else {
            let rendered: Vec<String> = args
                .iter()
                .map(|(name, expr)| format!("{name} = {expr}"))
                .collect();
            format!("t!(locale, \"{key}\", {})", rendered.join(", "))
        }
    }

    /// A string-valued site (`impl Into<String>` parameters such as
    /// `a11y::Link::new`/`Button::new`, `FormFor::override_label`, and Maud
    /// splice positions). `english` is the bare text; with `--i18n` off it is
    /// emitted as a quoted Rust literal, exactly as before.
    pub(super) fn lit(&self, key: &str, english: &str) -> String {
        if self.enabled {
            self.record(key, english, &[])
        } else {
            format!("\"{english}\"")
        }
    }

    /// [`Self::lit`] for a `&str` parameter (`layout(title)`,
    /// `widgets::Column::new`, `property_list` labels).
    pub(super) fn lit_ref(&self, key: &str, english: &str) -> String {
        if self.enabled {
            format!("&{}", self.record(key, english, &[]))
        } else {
            format!("\"{english}\"")
        }
    }

    /// [`Self::lit`] in Maud **body** position, where a bare literal renders as
    /// text but any expression must be parenthesised: `"Save"` becomes
    /// `(t!(locale, "common.save"))`.
    pub(super) fn markup(&self, key: &str, english: &str) -> String {
        if self.enabled {
            format!("({})", self.record(key, english, &[]))
        } else {
            format!("\"{english}\"")
        }
    }

    /// [`Self::expr`] in Maud body position.
    pub(super) fn markup_expr(
        &self,
        key: &str,
        ftl: &str,
        plain: &str,
        args: &[(&str, &str)],
    ) -> String {
        if self.enabled {
            format!("({})", self.record(key, ftl, args))
        } else {
            plain.to_owned()
        }
    }

    /// The general form: `plain` is the **complete** Rust expression the
    /// non-i18n scaffold emits (often a `format!(…)` call), `ftl` the Fluent
    /// value — which may carry `{ $arg }` placeholders fed by `args`, each a
    /// `(fluent name, Rust expression)` pair.
    pub(super) fn expr(&self, key: &str, ftl: &str, plain: &str, args: &[(&str, &str)]) -> String {
        if self.enabled {
            self.record(key, ftl, args)
        } else {
            plain.to_owned()
        }
    }

    /// [`Self::expr`] for a `&str` parameter.
    pub(super) fn expr_ref(
        &self,
        key: &str,
        ftl: &str,
        plain: &str,
        args: &[(&str, &str)],
    ) -> String {
        if self.enabled {
            format!("&{}", self.record(key, ftl, args))
        } else {
            plain.to_owned()
        }
    }
}

/// Split a `.ftl` source into its defined keys.
///
/// Mirrors the minimal parser in `autumn-macros`' `t!` validation and
/// `autumn-web`'s `Bundle` loader: a top-level `key = value` line, with `#`
/// comments and indented continuation lines skipped.
fn defined_keys(src: &str) -> BTreeMap<String, String> {
    src.lines()
        .filter(|line| {
            !line.trim_start().starts_with('#')
                && !line.trim().is_empty()
                && !line.starts_with(' ')
                && !line.starts_with('\t')
        })
        .filter_map(|line| line.split_once('='))
        .map(|(k, v)| (k.trim().to_owned(), v.trim().to_owned()))
        .collect()
}

/// Merge the keys a `--i18n` scaffold referenced into `existing` (the project's
/// `i18n/en.ftl`, or `""` when there is none yet).
///
/// Semantics, in order of importance:
///
/// 1. **A key that already exists is never rewritten.** Re-running the
///    generator over a file whose English has been edited — or whose keys a
///    translator has already worked from — must not clobber it.
/// 2. **Shared chrome is written once.** `common.*` keys land in one block that
///    later resources add to rather than duplicate (AC5).
/// 3. **The resource's own keys are grouped** under a marked comment, so a
///    translator reads the file by resource and `autumn destroy scaffold` can
///    remove exactly what this generator added.
///
/// Returns `existing` unchanged when every key is already defined, so the
/// generator can skip the write and leave the file out of the plan.
pub(super) fn merge_en_ftl(
    existing: &str,
    pascal_name: &str,
    resource: &str,
    keys: &BTreeMap<String, String>,
) -> String {
    use std::fmt::Write as _;

    let already = defined_keys(existing);
    let resource_prefix = format!("{resource}.");
    let resource_header = format!("{RESOURCE_HEADER_PREFIX}{pascal_name}{RESOURCE_HEADER_SUFFIX}");
    // A resource literally named `Common` would share its prefix with the chrome
    // block. `plan_scaffold_with_options_impl` refuses that name under `--i18n`;
    // classifying chrome FIRST and taking the resource's keys from what is left
    // is the belt-and-braces half, so no key can ever be written to both blocks
    // even from a hand-built plan.
    let missing_common: Vec<(&String, &String)> = keys
        .iter()
        .filter(|(k, _)| k.starts_with("common.") && !already.contains_key(*k))
        .collect();
    let missing_resource: Vec<(&String, &String)> = keys
        .iter()
        .filter(|(k, _)| {
            k.starts_with(&resource_prefix)
                && !k.starts_with("common.")
                && !already.contains_key(*k)
        })
        .collect();
    // Reconciled BEFORE the nothing-to-do check below: a regeneration that
    // dropped a field or a flag has every REMAINING key already present, so the
    // "missing" sets are empty while the block still carries keys the rewritten
    // routes no longer reference — exactly what `autumn i18n check --strict`
    // fails on. Values, comments, and blank lines for surviving keys carry over.
    //
    // The shared chrome is never pruned here: every resource writes those keys,
    // so dropping one from this resource's render would delete a key a SIBLING
    // still uses. Chrome is additive, and `destroy` is what eventually takes it.
    if let Some(reconciled) = reconcile_block(existing, &resource_header, &resource_prefix, keys) {
        return merge_en_ftl(&reconciled, pascal_name, resource, keys);
    }
    if missing_common.is_empty() && missing_resource.is_empty() {
        return existing.to_owned();
    }

    // Re-running the generator — after adding a column, or with a flag that
    // brings new chrome — must extend the block that already exists rather than
    // strand the new key at EOF under no header at all. The file's whole promise
    // to a translator is that it reads by section.
    if !missing_common.is_empty()
        && let Some(insert_at) = block_end(existing, COMMON_HEADER)
    {
        let mut out = String::with_capacity(existing.len() + missing_common.len() * 48);
        out.push_str(&existing[..insert_at]);
        for (key, value) in &missing_common {
            let _ = writeln!(out, "{key} = {value}");
        }
        out.push_str(&existing[insert_at..]);
        // Whatever the resource block still needs lands on the next pass, which
        // terminates: the chrome keys are now all present.
        return merge_en_ftl(&out, pascal_name, resource, keys);
    }

    let mut out = String::with_capacity(existing.len() + (keys.len() + 4) * 48);
    if existing.is_empty() {
        out.push_str(
            "# Generated by `autumn generate scaffold --i18n`.\n\
             #\n\
             # This is the DEFAULT locale — leave these values in their own language.\n\
             # To add a locale, copy this file to `i18n/<tag>.ftl` and translate THERE.\n\
             # Keys are grouped by resource; `common.*` is shared chrome every\n\
             # scaffolded resource reuses.\n\n",
        );
    } else {
        out.push_str(existing);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }

    if !missing_common.is_empty() {
        out.push_str(COMMON_HEADER);
        out.push('\n');
        for (key, value) in missing_common {
            let _ = writeln!(out, "{key} = {value}");
        }
        out.push_str(COMMON_FOOTER);
        out.push('\n');
        if !missing_resource.is_empty() {
            out.push('\n');
        }
    }
    if !missing_resource.is_empty() {
        if !existing.contains(&resource_header) {
            out.push_str(&resource_header);
            out.push('\n');
        }
        for (key, value) in missing_resource {
            let _ = writeln!(out, "{key} = {value}");
        }
        out.push_str(&block_footer(&resource_header));
        out.push('\n');
    }
    out
}

/// Rewrite the block `header` opens so its keys are exactly `keys`' entries
/// under `prefix`, or `None` when there is no such block or it already matches.
///
/// Existing VALUES win — a translated `post.new = Nouvel article` stays put —
/// and non-key lines (a translator's comment, a blank line grouping fields) are
/// carried through in place. Only keys the current render no longer references
/// are dropped, which is the whole point: they have no call sites left, so
/// `autumn i18n check --strict` would fail on them.
fn reconcile_block(
    existing: &str,
    header: &str,
    prefix: &str,
    keys: &BTreeMap<String, String>,
) -> Option<String> {
    use std::fmt::Write as _;
    let end = block_end(existing, header)?;
    let start = existing.find(header)?;
    let body_start = start + existing[start..].find('\n').map_or(0, |i| i + 1);
    // The `common.` exclusion applies only when reconciling a RESOURCE block —
    // a resource named `Common` is refused, but a hand-built plan could still
    // reach here. Pruning the chrome block passes `prefix == "common."`, where
    // the exclusion must not fire.
    let wanted: BTreeMap<&str, &str> = keys
        .iter()
        .filter(|(k, _)| {
            k.starts_with(prefix) && (prefix == "common." || !k.starts_with("common."))
        })
        .map(|(k, v)| (k.as_str(), v.as_str()))
        .collect();

    let mut body = String::new();
    let mut keeping_continuations = false;
    for line in existing[body_start..end].lines() {
        // INDENTATION decides first, before any `=` split. A Fluent
        // continuation is just indented text and usually contains no `=` at
        // all (`    and a second line`), so testing for `=` first would file it
        // as a comment and keep it even when its key is being dropped —
        // producing exactly the orphan this reconciliation exists to avoid:
        // the loader either rejects it or silently glues it onto the message
        // above.
        if line.starts_with(' ') || line.starts_with('\t') {
            if keeping_continuations {
                body.push_str(line);
                body.push('\n');
            }
            continue;
        }
        let Some((raw_key, _)) = line.split_once('=') else {
            // A comment or blank line at the block's own indentation — keep it
            // where the translator put it. It ends the previous key's value.
            keeping_continuations = false;
            body.push_str(line);
            body.push('\n');
            continue;
        };
        if wanted.contains_key(raw_key.trim()) {
            keeping_continuations = true;
            body.push_str(line);
            body.push('\n');
        } else {
            // Dropped: its continuation lines go with it.
            keeping_continuations = false;
        }
    }
    // Scanned over the WHOLE file, not just this block. A key can be defined
    // outside the block a translator never touched — hand-authored above it, or
    // left behind by an older layout — and appending a second definition here
    // would not merely duplicate it: `parse_ftl` inserts each entry into a map
    // in file order (`autumn/src/i18n.rs`), so the LAST definition wins. The
    // generated English would silently replace the translation above it, which
    // is the one thing this merge promises never to do. Reconciliation itself
    // still reads only the block: keys outside it are not the generator's to
    // keep or drop, just its to leave alone.
    let defined_anywhere = defined_keys(existing);
    for (key, value) in &wanted {
        if !defined_anywhere.contains_key(*key) {
            let _ = writeln!(body, "{key} = {value}");
        }
    }

    if body == existing[body_start..end] {
        return None;
    }
    let mut out = String::with_capacity(existing.len());
    out.push_str(&existing[..body_start]);
    out.push_str(&body);
    out.push_str(&existing[end..]);
    Some(out)
}

/// Byte offset just past the last key line of the block `header` introduces, or
/// `None` when `existing` carries no such block. Used for both the shared
/// chrome block and a resource's own.
///
/// The block runs from its header to the first blank line or foreign comment —
/// the same shape [`merge_en_ftl`] writes.
fn block_end(existing: &str, header: &str) -> Option<usize> {
    let start = existing.find(header)?;
    let mut cursor = start + header.len();
    // Step past the header's own newline.
    cursor += existing[cursor..].find('\n').map_or(0, |i| i + 1);
    let footer = block_footer(header);
    let mut end = cursor;
    for line in existing[cursor..].split_inclusive('\n') {
        if line.trim_end() == footer {
            return Some(end);
        }
        end += line.len();
    }
    // No footer: a bundle written before blocks were explicitly closed. Fall
    // back to the old boundary — the first blank line or foreign comment — so
    // an existing project still merges and destroys correctly.
    let mut end = cursor;
    for line in existing[cursor..].split_inclusive('\n') {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            break;
        }
        end += line.len();
    }
    Some(end)
}

/// Inverse of [`merge_en_ftl`] for `autumn destroy scaffold` — remove one
/// resource's block (its marked comment plus every `<resource>.` key) from
/// `existing`.
///
/// The shared `common.*` block is deliberately left alone: other scaffolded
/// resources reuse it, and it is what keeps the file non-empty. That matters —
/// the generated app calls `.i18n_auto()`, which panics at startup if the
/// default locale's file is missing, so destroy must never empty or delete it.
pub(super) fn remove_en_ftl_keys(
    existing: &str,
    pascal_name: &str,
    resource: &str,
    // The `common.*` keys a surviving route module still looks up. The caller
    // scans the project for these, because the bundle itself cannot answer it:
    // a resource whose keys were all hand-authored before it was scaffolded
    // leaves no marker comment behind, so "no other marker" does NOT mean "no
    // other user".
    surviving_chrome: &std::collections::HashSet<String>,
) -> String {
    let stripped = remove_resource_block(existing, pascal_name, resource);
    // Chrome exists to be shared. Once nothing references it, every `common.*`
    // key is dead weight — which is exactly what `autumn i18n check --strict`
    // fails on, so destroying the only `--i18n` resource would otherwise leave
    // the project's own lint red. But the asymmetry matters: an orphan key is a
    // lint warning, while removing one a surviving resource still calls is a
    // COMPILE error (`t!` validates key existence at compile time). So this errs
    // toward keeping.
    //
    // Never the FILE, either way: `.i18n_auto()` panics at startup when the
    // default locale's bundle is missing, and a comment-only bundle still loads.
    prune_chrome_block(&stripped, surviving_chrome)
}

/// Narrow the shared chrome block to the keys `surviving` still names, dropping
/// the block entirely when nothing is left.
///
/// Per KEY, not all-or-nothing. Chrome is per-surface: `common.trash`,
/// `common.restore` and `common.purge` come from `--soft-delete`, `common.next`
/// from the pager, `common.export.csv` from the CSV link. Destroying the only
/// resource that had a Trash view leaves those three referenced by nothing —
/// which `autumn i18n check --strict` fails on — while `common.create`,
/// `common.save` and the rest are still in use by every sibling and must stay.
///
/// Marker-bounded like [`remove_marked_block`], so a hand-authored `common.*`
/// key outside the block is never touched.
fn prune_chrome_block(existing: &str, surviving: &std::collections::HashSet<String>) -> String {
    if surviving.is_empty() {
        return remove_marked_block(existing, COMMON_HEADER);
    }
    let kept: BTreeMap<String, String> = surviving
        .iter()
        .map(|k| (k.clone(), String::new()))
        .collect();
    // `reconcile_block` keeps each surviving key's own value and drops the
    // rest — the empty values above are never written, since every key it keeps
    // is already present in the block.
    reconcile_block(existing, COMMON_HEADER, "common.", &kept)
        .unwrap_or_else(|| existing.to_owned())
}

fn remove_resource_block(existing: &str, pascal_name: &str, _resource: &str) -> String {
    let header = format!("{RESOURCE_HEADER_PREFIX}{pascal_name}{RESOURCE_HEADER_SUFFIX}");
    remove_marked_block(existing, &header)
}

/// Remove the marked comment `header` and the run of key lines it introduces.
///
/// Bounded by the MARKER, not by key prefix. A prefix sweep would also delete a
/// hand-authored `post.email.subject` — a translation the application owns,
/// which this generator never wrote and has no business removing — purely
/// because it happens to start with the resource's name. The merge path goes to
/// some trouble never to overwrite a value somebody else authored; destroy has
/// to be equally careful about what it takes away. So removal covers exactly
/// the block `merge_en_ftl` writes: the header line, then every following line
/// up to the first blank line or foreign comment.
///
/// That run includes any INDENTED continuation lines. Leaving those behind is
/// how a destroy corrupts a bundle: the loader either rejects the orphan
/// outright — and `.i18n_auto()` turns that into a startup panic — or silently
/// glues it onto whichever key precedes it, rewriting an unrelated translation.
fn remove_marked_block(existing: &str, header: &str) -> String {
    let Some(end) = block_end(existing, header) else {
        return existing.to_owned();
    };
    let start = existing.find(header).expect("block_end found the header");
    // `block_end` stops just BEFORE the closing marker; take that line too.
    let footer = block_footer(header);
    let end = existing[end..]
        .strip_prefix(footer.as_str())
        .map_or(end, |rest| {
            end + footer.len() + usize::from(rest.starts_with('\n'))
        });
    let mut out = String::with_capacity(existing.len());
    out.push_str(&existing[..start]);
    out.push_str(&existing[end..]);
    let lines: Vec<&str> = out.lines().collect();
    collapse_blank_runs(&lines)
}

/// Re-join `lines`, collapsing the blank runs a removed block leaves behind and
/// restoring the file's single trailing newline.
fn collapse_blank_runs(lines: &[&str]) -> String {
    let mut joined = String::with_capacity(lines.iter().map(|l| l.len() + 1).sum());
    let mut prev_blank = false;
    for line in lines {
        let blank = line.trim().is_empty();
        if blank && prev_blank {
            continue;
        }
        prev_blank = blank;
        joined.push_str(line);
        joined.push('\n');
    }
    while joined.ends_with("\n\n") {
        joined.pop();
    }
    joined
}

/// The name of the TOML table `line` opens, if it opens one.
///
/// Tolerates the spacing and trailing comments TOML allows — `[ i18n ]` and
/// `[i18n] # locale settings` are both the i18n table. Getting this wrong is not
/// cosmetic: missing an existing table makes the generator append a SECOND
/// `[i18n]`, and a duplicate table makes the whole file unparseable, taking the
/// application's entire configuration down with it.
fn toml_table_name(line: &str) -> Option<&str> {
    let trimmed = line.trim();
    let rest = trimmed.strip_prefix('[')?;
    let close = rest.find(']')?;
    // Anything after the closing bracket must be blank or a comment — otherwise
    // this is not a table header at all.
    let tail = rest[close + 1..].trim();
    if !tail.is_empty() && !tail.starts_with('#') {
        return None;
    }
    Some(rest[..close].trim())
}

/// The scalar on the right of a TOML `key = value`, unquoted, with any trailing
/// comment removed.
///
/// The comment has to be stripped with the quoting in mind, not before it: `#`
/// is an ordinary character inside a string, so cutting at the first `#` would
/// mangle `dir = "i18n#v2"`, while ignoring comments entirely turns
/// `default_locale = "fr" # our default` into the locale tag
/// `fr" # our default` — and the generator would then cheerfully create a file
/// named after it. Returns `None` for an empty or unparseable value.
fn toml_scalar_value(raw: &str) -> Option<String> {
    let trimmed = raw.trim_start();
    let quote = trimmed.chars().next()?;
    let value = if quote == '"' || quote == '\'' {
        let rest = &trimmed[quote.len_utf8()..];
        // A BASIC string (double quotes) processes escapes; a LITERAL string
        // (single quotes) does not, by TOML's definition. Both of these values
        // become filesystem paths, so the raw source text is the wrong thing to
        // build them from: the app's loader reads the DECODED value, and
        // `dir = "i18n\\bundles"` on Windows would otherwise have the generator
        // writing to a directory with a literal double backslash in its name
        // while the runtime reads the single-backslash one.
        //
        // The terminator has to respect escapes for the same reason: a `\"` is
        // part of the value, so stopping at it would truncate the path.
        if quote == '"' {
            let mut end = None;
            let mut escaped = false;
            for (i, c) in rest.char_indices() {
                if escaped {
                    escaped = false;
                } else if c == '\\' {
                    escaped = true;
                } else if c == '"' {
                    end = Some(i);
                    break;
                }
            }
            decode_toml_escapes(&rest[..end?])
        } else {
            rest[..rest.find(quote)?].to_owned()
        }
    } else {
        // A bare value runs to the first comment marker or end of line.
        trimmed
            .split_once('#')
            .map_or(trimmed, |(before, _)| before)
            .trim_end()
            .to_owned()
    };
    (!value.is_empty()).then_some(value)
}

/// Split an inline table's body on the commas that separate its members.
///
/// Quote-aware: a comma inside a value belongs to the value. `dir =
/// "translations,v2"` is a legal directory name, and splitting through it
/// leaves `toml_scalar_value` with an unterminated string, which it discards —
/// so the generator would silently fall back to `i18n/` and write its keys
/// where the runtime never looks.
///
/// Escapes are honoured while scanning so a `\"` inside a basic string does not
/// end it. Literal (single-quoted) strings process no escapes, per TOML.
fn split_inline_members(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut current = String::new();
    let mut quote: Option<char> = None;
    let mut escaped = false;
    for c in body.chars() {
        match quote {
            Some(q) => {
                current.push(c);
                if escaped {
                    escaped = false;
                } else if c == '\\' && q == '"' {
                    escaped = true;
                } else if c == q {
                    quote = None;
                }
            }
            None if c == '"' || c == '\'' => {
                quote = Some(c);
                current.push(c);
            }
            None if c == ',' => out.push(std::mem::take(&mut current)),
            None => current.push(c),
        }
    }
    out.push(current);
    out
}

/// Render `value` as the contents of a Rust double-quoted string literal.
///
/// A configured `dir` is interpolated into generated Rust (`embed_locales!`),
/// and TOML happily carries characters that Rust's lexer reads as escapes: the
/// Windows-shaped `dir = 'translations\bundles'` would emit `\b`, which is not
/// a Rust escape at all, so the generated `main.rs` stops parsing — before any
/// embed build, and for a project that merely configured a directory.
fn rust_string_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Decode the escape sequences TOML defines for a basic string.
///
/// An unknown or malformed escape is passed through verbatim rather than
/// rejected: this is a best-effort read of a file the app's own loader
/// validates properly, and a generator that refused to run over a `dir` it
/// could not decode would be worse than one that used the text as written.
fn decode_toml_escapes(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    let mut chars = src.chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        let Some(esc) = chars.next() else {
            out.push('\\');
            break;
        };
        match esc {
            'b' => out.push('\u{8}'),
            't' => out.push('\t'),
            'n' => out.push('\n'),
            'f' => out.push('\u{c}'),
            'r' => out.push('\r'),
            '"' => out.push('"'),
            '\\' => out.push('\\'),
            'u' | 'U' => {
                let width = if esc == 'u' { 4 } else { 8 };
                let digits: String = chars.clone().take(width).collect();
                if let Some(decoded) = u32::from_str_radix(&digits, 16)
                    .ok()
                    .filter(|_| digits.len() == width)
                    .and_then(char::from_u32)
                {
                    out.push(decoded);
                    for _ in 0..width {
                        chars.next();
                    }
                } else {
                    out.push('\\');
                    out.push(esc);
                }
            }
            other => {
                out.push('\\');
                out.push(other);
            }
        }
    }
    out
}

/// Whether `autumn.toml` already defines i18n configuration **in any of TOML's
/// spellings**, so a second definition must not be appended.
///
/// TOML expresses the same table three ways, and all three collide with an
/// appended `[i18n]`:
///
/// ```toml
/// [i18n]                                       # a table header
/// i18n = { default_locale = "fr" }             # an inline table
/// i18n.default_locale = "fr"                   # a dotted key
/// ```
///
/// Missing any of them is not cosmetic: the generator appends `[i18n]`, TOML
/// rejects the duplicate definition, and the application can no longer load its
/// configuration at all. A dotted `i18n.x` under some other table
/// (`[server]\ni18n.x = …`) is a different key entirely, so only top-level ones
/// count.
fn defines_i18n(autumn_toml: &str) -> bool {
    let mut at_top_level = true;
    for line in autumn_toml.lines() {
        if let Some(name) = toml_table_name(line) {
            if name == "i18n" {
                return true;
            }
            at_top_level = false;
            continue;
        }
        if !at_top_level {
            continue;
        }
        let trimmed = line.trim();
        if let Some((key, _)) = trimmed.split_once('=') {
            let key = key.trim();
            if key == "i18n" || key.starts_with("i18n.") {
                return true;
            }
        }
    }
    false
}

/// What an existing `autumn.toml` configures for i18n: the default locale, and
/// the directory its bundles live in.
///
/// Both matter for where the generated keys go. The runtime resolves lookups
/// through `<dir>/<default_locale>.ftl`, so writing to a hardcoded
/// `i18n/en.ftl` in a project configured otherwise leaves the app's real bundle
/// without a single generated key: every label renders as a visible `{$key}`
/// placeholder, and `autumn i18n check` reports them all missing — while `t!`'s
/// compile-time validation (which looks under `i18n/` for `en` by default)
/// passes, so nothing catches it until runtime.
///
/// Deliberately a line scan rather than a TOML parse: this needs two keys, the
/// file may carry profile overlays the generator has no business interpreting,
/// and a malformed `autumn.toml` should not fail generation here — the app's own
/// loader reports that far better. `[profile.<env>.i18n]` overlays are ignored:
/// the generator writes the base bundle, which every profile inherits.
pub(super) fn configured_i18n(autumn_toml: &str) -> (Option<String>, Option<String>) {
    let mut in_i18n = false;
    let mut at_top_level = true;
    let (mut locale, mut dir) = (None, None);
    for line in autumn_toml.lines() {
        if let Some(name) = toml_table_name(line) {
            in_i18n = name == "i18n";
            at_top_level = false;
            continue;
        }
        let trimmed = line.trim();
        let Some((raw_key, value)) = trimmed.split_once('=') else {
            continue;
        };
        // Dotted keys (`i18n.default_locale = "fr"`) carry the table in the key
        // itself, so they are read at top level rather than inside `[i18n]`.
        let (key, value) = if in_i18n {
            (raw_key, value)
        } else if at_top_level {
            match raw_key.trim().strip_prefix("i18n.") {
                Some(rest) => (rest, value),
                // An inline `i18n = { default_locale = "fr", … }`: read the
                // members out of the braces.
                None if raw_key.trim() == "i18n" => {
                    for member in
                        split_inline_members(value.trim().trim_matches(|c| c == '{' || c == '}'))
                    {
                        let member = member.as_str();
                        let Some((k, v)) = member.split_once('=') else {
                            continue;
                        };
                        let Some(v) = toml_scalar_value(v) else {
                            continue;
                        };
                        match k.trim() {
                            "default_locale" => locale = Some(v.clone()),
                            "dir" => dir = Some(v.clone()),
                            _ => {}
                        }
                    }
                    continue;
                }
                None => continue,
            }
        } else {
            continue;
        };
        let Some(value) = toml_scalar_value(value) else {
            continue;
        };
        match key.trim() {
            "default_locale" => locale = Some(value.clone()),
            "dir" => dir = Some(value.clone()),
            _ => {}
        }
    }
    (locale, dir)
}

/// Embed the locale bundle into the binary for `autumn build --embed`,
/// matching what `autumn new --with-i18n` wires into a fresh app.
///
/// `.i18n_auto()` alone loads from DISK. An `--embed` build is supposed to be
/// self-contained, so without this the binary still reaches for the locale
/// directory at startup: run it from an empty deployment directory — or from
/// the release image, whose embedded-build path deliberately ships no sidecar —
/// and it panics on a missing default bundle, after a build that looked
/// entirely clean.
///
/// Both edits sit behind the `embed-assets` feature the template already gates
/// its static assets on, and both anchor on the `EMBEDDED_STATIC` lines that
/// `autumn new` emits. Returns `None` when those are absent (an `--api` or
/// hand-rolled `main.rs`), so the caller can leave it alone; returns the input
/// unchanged when the locales are already embedded.
pub(super) fn ensure_embedded_locales(main_rs: &str, dir: &str) -> Option<String> {
    const STATIC_ANCHOR: &str =
        "static EMBEDDED_STATIC: autumn_web::include_dir::Dir = autumn_web::embed_static!();";
    const INSTALL_ANCHOR: &str = "    let app = app.embedded_static(&EMBEDDED_STATIC);\n";
    // `embed_locales!()` defaults to `i18n/`; a configured directory is passed
    // through as the macro's literal argument — escaped, because this is the one
    // place a `dir` read out of `autumn.toml` becomes Rust source.
    let macro_call = if dir == "i18n" {
        "autumn_web::embed_locales!()".to_owned()
    } else {
        format!(
            "autumn_web::embed_locales!(\"{}\")",
            rust_string_escape(dir)
        )
    };
    if main_rs.contains("EMBEDDED_LOCALES") {
        // Already embedded — but not necessarily from the right place. A
        // project that changed `[i18n] dir` after its first `--i18n` scaffold
        // keeps embedding the OLD directory while the keys, the Docker `COPY`,
        // and the runtime load all move to the new one, so an `--embed` build
        // ships a bundle the app never reads. Repoint it.
        if main_rs.contains(&macro_call) {
            return Some(main_rs.to_owned());
        }
        let Some(call_at) = main_rs.find("autumn_web::embed_locales!") else {
            // Someone hand-rolled the static; leave it entirely alone.
            return Some(main_rs.to_owned());
        };
        let end = main_rs[call_at..].find(';')? + call_at;
        return Some(format!(
            "{}{macro_call}{}",
            &main_rs[..call_at],
            &main_rs[end..]
        ));
    }
    if !main_rs.contains(STATIC_ANCHOR) || !main_rs.contains(INSTALL_ANCHOR) {
        return None;
    }
    let with_static = main_rs.replacen(
        STATIC_ANCHOR,
        &format!(
            "{STATIC_ANCHOR}\n#[cfg(feature = \"embed-assets\")]\n\
             static EMBEDDED_LOCALES: autumn_web::include_dir::Dir = {macro_call};"
        ),
        1,
    );
    Some(with_static.replacen(
        INSTALL_ANCHOR,
        &format!(
            "{INSTALL_ANCHOR}    #[cfg(feature = \"embed-assets\")]\n\
             \x20   let app = app.embedded_locales(&EMBEDDED_LOCALES);\n"
        ),
        1,
    ))
}

/// Ship the `i18n/` sidecar into a generated `Dockerfile`, in both stages.
///
/// `.i18n_auto()` reads `i18n/<default>.ftl` from the working directory at
/// startup and **panics** when it is missing (`autumn/src/app.rs`'s
/// `resolve_i18n_bundle`). `autumn new --with-i18n` handles this by resolving
/// the Dockerfile's i18n anchors; a plain `autumn new` strips them, so a project
/// that adopts `--i18n` later builds an image with no bundle in it and
/// crash-loops on deploy — after a build that looked completely clean, because
/// `t!`'s compile-time key check silently degrades to a runtime lookup when the
/// file is absent from the build context.
///
/// The two `COPY` lines are inserted next to the ones for `migrations/`, which
/// both stages already carry and which sit at exactly the same layer. Returns
/// `None` when the file has no such anchor (a hand-edited or absent Dockerfile),
/// so the caller can warn instead of guessing where to write.
pub(super) fn ensure_dockerfile_i18n_copy(dockerfile: &str, dir: &str) -> Option<String> {
    let builder_anchor = "COPY migrations ./migrations";
    let runtime_anchor = "COPY --from=builder /app/migrations /app/migrations";
    let builder_line = format!("COPY {dir} ./{dir}");
    let runtime_line = format!("COPY --from=builder /app/{dir} /app/{dir}");
    if dockerfile.contains(&builder_line) && dockerfile.contains(&runtime_line) {
        return Some(dockerfile.to_owned());
    }
    if !dockerfile.contains(builder_anchor) || !dockerfile.contains(runtime_anchor) {
        return None;
    }
    // Runtime stage first: its anchor is a superstring-free, later occurrence,
    // and replacing the builder anchor first would shift it.
    let out = dockerfile.replacen(
        runtime_anchor,
        &format!("{runtime_anchor}\n{runtime_line}"),
        1,
    );
    Some(out.replacen(
        builder_anchor,
        &format!("{builder_anchor}\n{builder_line}"),
        1,
    ))
}

/// The directory an earlier `--i18n` run pointed the Dockerfile's locale
/// `COPY` lines at, when that is no longer the configured `dir`.
///
/// A project that changes `[i18n] dir` after its first `--i18n` scaffold keeps
/// the old pair, and `ensure_dockerfile_i18n_copy` adds a second one for the
/// new directory. That is worth saying out loud: `COPY` fails the build when
/// its source is missing from the context, so a rename that MOVED the old
/// directory stops the image building at all, and one that merely copied it
/// ships a bundle the app never reads.
///
/// Reported rather than rewritten. These lines carry no marker, so "the
/// generator wrote this" can only ever be inferred — and the inference is a
/// shape (`COPY <x> ./<x>`) that an ordinary hand-written `COPY static
/// ./static` matches exactly. A warning that occasionally names the wrong
/// directory costs the reader a second; an edit that silently rewrites
/// someone's asset `COPY` into a locale one costs them their image. So the
/// position is used as corroboration (this generator inserts immediately after
/// the `migrations` anchors) and the result is still only ever advice.
pub(super) fn stale_dockerfile_i18n_dir(dockerfile: &str, dir: &str) -> Option<String> {
    /// The directory in `COPY <x> ./<x>`, when the line has that exact shape.
    fn builder_copy_dir(line: &str) -> Option<&str> {
        match line.split_whitespace().collect::<Vec<_>>().as_slice() {
            ["COPY", src, dest] if dest.strip_prefix("./") == Some(*src) => Some(src),
            _ => None,
        }
    }
    /// The same for `COPY --from=builder /app/<x> /app/<x>`.
    fn runtime_copy_dir(line: &str) -> Option<&str> {
        match line.split_whitespace().collect::<Vec<_>>().as_slice() {
            ["COPY", "--from=builder", src, dest] if src == dest => {
                src.strip_prefix("/app/").filter(|d| !d.contains('/'))
            }
            _ => None,
        }
    }

    let after = |anchor: &str, extract: fn(&str) -> Option<&str>| -> Option<String> {
        let mut lines = dockerfile.lines().skip_while(|l| l.trim() != anchor);
        lines.next()?;
        extract(lines.next()?).map(str::to_owned)
    };

    let builder = after("COPY migrations ./migrations", builder_copy_dir)?;
    let runtime = after(
        "COPY --from=builder /app/migrations /app/migrations",
        runtime_copy_dir,
    )?;
    // Both stages naming the same non-configured directory is what makes this a
    // moved bundle rather than a coincidence.
    (builder == runtime && builder != dir).then_some(builder)
}

/// Profile overlays that point i18n somewhere other than the base config.
///
/// `[profile.prod.i18n]` (and the sibling `autumn-<env>.toml` files) can
/// override `dir` and `default_locale`, and the runtime resolves the FULLY
/// LAYERED config — so a base of `i18n/en.ftl` with a production override of
/// `dir = "translations"` means the image ships `i18n/` while the app boots
/// looking for `translations/`, and `.i18n_auto()` panics.
///
/// The generator deliberately writes the BASE bundle only. Writing English into
/// a profile that exists precisely because it serves a different locale would
/// be its own bug, and there is no way to know which profile a given deploy
/// uses — so this reports the overlays instead, and the caller warns. Returns
/// the `(profile, dir/locale summary)` pairs that differ from the base.
pub(super) fn profile_i18n_overrides(
    autumn_toml: &str,
    base_dir: &str,
    base_locale: &str,
) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut current: Option<String> = None;
    let (mut dir, mut locale) = (None, None);
    let mut flush = |profile: Option<String>, dir: Option<String>, locale: Option<String>| {
        let Some(profile) = profile else { return };
        let differs = dir.as_deref().is_some_and(|d| d != base_dir)
            || locale.as_deref().is_some_and(|l| l != base_locale);
        if !differs {
            return;
        }
        let path = format!(
            "{}/{}.ftl",
            dir.as_deref().unwrap_or(base_dir),
            locale.as_deref().unwrap_or(base_locale)
        );
        out.push((profile, path));
    };
    for line in autumn_toml.lines() {
        if let Some(name) = toml_table_name(line) {
            flush(current.take(), dir.take(), locale.take());
            // `[profile.<env>.i18n]`
            current = name
                .strip_prefix("profile.")
                .and_then(|rest| rest.strip_suffix(".i18n"))
                .map(str::to_owned);
            continue;
        }
        if current.is_none() {
            continue;
        }
        let trimmed = line.trim();
        let Some((key, value)) = trimmed.split_once('=') else {
            continue;
        };
        let Some(value) = toml_scalar_value(value) else {
            continue;
        };
        match key.trim() {
            "default_locale" => locale = Some(value.clone()),
            "dir" => dir = Some(value.clone()),
            _ => {}
        }
    }
    flush(current, dir, locale);
    out
}

/// Add an `[i18n]` block to `autumn.toml` if it has none.
///
/// `default_locale = "en"` matches the `en.ftl` the generator writes; the
/// supported list starts as `["en"]` so an app that adds `fr.ftl` only has to
/// extend one line. A project that already configures `[i18n]` is left alone —
/// its `default_locale` may not be `en`, and rewriting it would silently
/// repoint the bundle the app loads.
pub(super) fn ensure_i18n_config_block(existing: &str) -> String {
    // Match the CONFIGURATION, not the literal text — see `defines_i18n`.
    if defines_i18n(existing) {
        return existing.to_owned();
    }
    let mut out = existing.to_owned();
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out.push_str("[i18n]\ndefault_locale = \"en\"\nsupported_locales = [\"en\"]\n");
    out
}

/// Byte offsets of every `needle` in `src` that is REAL CODE — not inside a
/// line comment, a (nestable) block comment, a string or raw-string literal, or
/// a char literal.
///
/// `autumn new`'s own template carries the line
/// `// Register new endpoints by adding them to the .routes(routes![...]) list`
/// right above `fn main`, and a naive `find(".routes(")` lands there: the
/// `.i18n_auto()` call gets written into a COMMENT, the builder chain is never
/// touched, and the idempotency guard then makes every later run a no-op. The
/// app compiles, starts, and renders raw keys forever with no error anywhere.
/// Same class of decoy — and the same lexical defence — as
/// [`has_shared_layout`](super::scaffold::has_shared_layout).
fn real_offsets(src: &str, needle: &str) -> Vec<usize> {
    let bytes = src.as_bytes();
    let n = needle.as_bytes();
    let mut out = Vec::new();
    let mut i = 0usize;
    let mut block_depth = 0usize;
    while i < bytes.len() {
        if block_depth > 0 {
            if bytes[i..].starts_with(b"/*") {
                block_depth += 1;
                i += 2;
            } else if bytes[i..].starts_with(b"*/") {
                block_depth -= 1;
                i += 2;
            } else {
                i += 1;
            }
            continue;
        }
        if bytes[i..].starts_with(b"//") {
            i += src[i..].find('\n').map_or(src.len() - i, |nl| nl + 1);
            continue;
        }
        if bytes[i..].starts_with(b"/*") {
            block_depth = 1;
            i += 2;
            continue;
        }
        if is_raw_string_start(bytes, i) {
            i = skip_raw_string(bytes, i);
            continue;
        }
        if bytes[i] == b'"' {
            i += 1;
            while i < bytes.len() && bytes[i] != b'"' {
                i += usize::from(bytes[i] == b'\\') + 1;
            }
            i += 1;
            continue;
        }
        if bytes[i..].starts_with(n) {
            out.push(i);
            i += n.len();
            continue;
        }
        i += 1;
    }
    out
}

/// The outcome of trying to wire `.i18n_auto()` into `main.rs`.
#[derive(Debug, PartialEq, Eq)]
pub(super) enum I18nAutoWiring {
    /// The builder chain now calls `.i18n_auto()` (or already did).
    Wired(String),
    /// The app installs its own `Bundle` with `.i18n(...)` — from embedded
    /// files, a translation-management service, memory. That bundle takes
    /// precedence over any filesystem load, so the keys this generator wrote to
    /// disk will never reach it, and every generated label renders as a
    /// placeholder even though generation and `t!`'s compile-time check both
    /// succeeded. `main.rs` is left alone (swapping someone's bundle for a
    /// filesystem load would be worse) and the caller warns.
    CustomBundle,
    /// No real `.routes(` call was found, so there is nowhere safe to insert.
    /// The caller surfaces this as a plan warning rather than writing the call
    /// into a comment, where it would silently never run.
    NoAnchor,
}

/// Insert `.i18n_auto()` into the `AppBuilder` chain in `main.rs` so the
/// generated `t!` lookups actually resolve (AC4's "zero further config").
///
/// Inserted immediately before the first REAL `.routes(` call — the same anchor
/// `autumn new --with-i18n` uses, but found with a comment/string-aware scan
/// (see [`real_offsets`]). A `main.rs` that already installs a
/// bundle — `.i18n_auto()` or an explicit `.i18n(...)` — is left untouched: an
/// app that built its own `Bundle` from embedded files or a
/// translation-management service must not have it swapped for a filesystem
/// load.
pub(super) fn ensure_i18n_auto(main_rs: &str) -> I18nAutoWiring {
    if !real_offsets(main_rs, ".i18n_auto()").is_empty() {
        return I18nAutoWiring::Wired(main_rs.to_owned());
    }
    if !real_offsets(main_rs, ".i18n(").is_empty() {
        return I18nAutoWiring::CustomBundle;
    }
    // Prefer a builder inside `fn main`. A `main.rs` can hold more than one —
    // a preview or test-only router next to the one the binary runs — and
    // wiring the wrong one is silent: the production app gets no bundle and
    // renders raw keys, while the idempotency guard above stops any later run
    // from correcting it. Falling back to the first overall keeps the common
    // `fn main` -> `build_app()` shape working, where there is only one anyway.
    let offsets = real_offsets(main_rs, ".routes(");
    let main_fn_at = real_offsets(main_rs, "fn main").first().copied();
    let anchor = main_fn_at
        .and_then(|at| offsets.iter().find(|&&o| o > at).copied())
        .or_else(|| offsets.first().copied());
    let Some(anchor) = anchor else {
        return I18nAutoWiring::NoAnchor;
    };
    // Reuse the anchor line's own indentation so the inserted call sits in the
    // builder chain rather than at some arbitrary column.
    let line_start = main_rs[..anchor].rfind('\n').map_or(0, |i| i + 1);
    if !main_rs[line_start..anchor].trim_start().is_empty() {
        // `.routes(` is not the first token on its line (e.g. a single-line
        // builder chain). Insert inline, which is still valid Rust.
        return I18nAutoWiring::Wired(format!(
            "{}.i18n_auto(){}",
            &main_rs[..anchor],
            &main_rs[anchor..]
        ));
    }
    let indent: String = main_rs[line_start..anchor]
        .chars()
        .take_while(|c| c.is_whitespace())
        .collect();
    I18nAutoWiring::Wired(format!(
        "{}{indent}.i18n_auto()\n{}",
        &main_rs[..line_start],
        &main_rs[line_start..]
    ))
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::*;

    fn chrome(keys: &[&str]) -> HashSet<String> {
        keys.iter().map(|k| (*k).to_owned()).collect()
    }

    fn keys(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
            .collect()
    }

    #[test]
    fn disabled_emitter_is_an_identity_over_the_plain_expression() {
        let labels = ViewLabels::disabled();
        assert_eq!(labels.lit("common.create", "Create"), "\"Create\"");
        assert_eq!(
            labels.lit_ref("post.index.title", "Post index"),
            "\"Post index\""
        );
        assert_eq!(
            labels.expr(
                "post.show.title",
                "Post #{ $id }",
                "&format!(\"Post #{}\", id)",
                &[]
            ),
            "&format!(\"Post #{}\", id)"
        );
        assert!(labels.used_keys().is_empty());
    }

    #[test]
    fn enabled_emitter_records_keys_and_emits_lookups() {
        let labels = ViewLabels::new(true);
        assert_eq!(
            labels.lit("common.create", "Create"),
            "t!(locale, \"common.create\")"
        );
        assert_eq!(
            labels.lit_ref("post.index.title", "Post index"),
            "&t!(locale, \"post.index.title\")"
        );
        assert_eq!(
            labels.expr(
                "common.new",
                "New { $resource }",
                "\"New Post\"",
                &[("resource", "&l_resource")]
            ),
            "t!(locale, \"common.new\", resource = &l_resource)"
        );
        let used = labels.used_keys();
        assert_eq!(used.get("common.create").unwrap(), "Create");
        assert_eq!(used.get("common.new").unwrap(), "New { $resource }");
    }

    #[test]
    fn merge_writes_a_header_and_both_blocks_into_an_empty_file() {
        let out = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.name", "Post")]),
        );
        assert!(out.contains(COMMON_HEADER), "{out}");
        assert!(out.contains("common.create = Create"), "{out}");
        assert!(out.contains("post.name = Post"), "{out}");
        assert!(out.contains("Post — generated by"), "{out}");
    }

    #[test]
    fn merge_never_rewrites_an_existing_value() {
        let existing = "common.create = Add\n";
        let out = merge_en_ftl(
            existing,
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.name", "Post")]),
        );
        assert!(out.contains("common.create = Add"), "{out}");
        assert!(!out.contains("common.create = Create"), "{out}");
        assert!(out.contains("post.name = Post"), "{out}");
    }

    #[test]
    fn merge_is_idempotent() {
        let pairs = keys(&[("common.create", "Create"), ("post.name", "Post")]);
        let once = merge_en_ftl("", "Post", "post", &pairs);
        let twice = merge_en_ftl(&once, "Post", "post", &pairs);
        assert_eq!(once, twice);
    }

    #[test]
    fn merge_shares_the_common_block_across_resources() {
        let first = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.name", "Post")]),
        );
        let second = merge_en_ftl(
            &first,
            "Comment",
            "comment",
            &keys(&[("common.create", "Create"), ("comment.name", "Comment")]),
        );
        assert_eq!(second.matches("common.create =").count(), 1, "{second}");
        assert_eq!(second.matches(COMMON_HEADER).count(), 1, "{second}");
        assert!(second.contains("comment.name = Comment"), "{second}");
        assert!(second.contains("post.name = Post"), "{second}");
    }

    #[test]
    fn remove_takes_only_the_resource_block() {
        // A sibling resource keeps the shared chrome in use, so only `Post`'s
        // own block comes out. (Destroying the LAST resource takes the chrome
        // too — see `removing_the_last_resource_takes_the_now_unreferenced_chrome_with_it`.)
        let ftl = merge_en_ftl(
            &merge_en_ftl(
                "",
                "Post",
                "post",
                &keys(&[("common.create", "Create"), ("post.name", "Post")]),
            ),
            "Comment",
            "comment",
            &keys(&[("common.create", "Create"), ("comment.name", "Comment")]),
        );
        // `true`: the surviving `Comment` routes still look chrome keys up.
        let out = remove_en_ftl_keys(&ftl, "Post", "post", &chrome(&["common.create"]));
        assert!(out.contains("common.create = Create"), "{out}");
        assert!(!out.contains("post.name"), "{out}");
        assert!(!out.contains("Post — generated by"), "{out}");
        assert!(out.contains("comment.name = Comment"), "{out}");
        // Idempotent: destroying twice is a no-op.
        assert_eq!(
            remove_en_ftl_keys(&out, "Post", "post", &chrome(&["common.create"])),
            out
        );
    }

    #[test]
    fn remove_leaves_a_sibling_resource_intact() {
        let ftl = merge_en_ftl(
            &merge_en_ftl("", "Post", "post", &keys(&[("post.name", "Post")])),
            "Comment",
            "comment",
            &keys(&[("comment.name", "Comment")]),
        );
        let out = remove_en_ftl_keys(&ftl, "Post", "post", &HashSet::new());
        assert!(out.contains("comment.name = Comment"), "{out}");
        assert!(!out.contains("post.name"), "{out}");
    }

    #[test]
    fn config_block_is_added_once() {
        let once = ensure_i18n_config_block("[server]\nport = 3000\n");
        assert!(once.contains("[i18n]"), "{once}");
        assert!(once.contains("default_locale = \"en\""), "{once}");
        assert_eq!(ensure_i18n_config_block(&once), once);
    }

    #[test]
    fn config_block_respects_an_existing_i18n_section() {
        let existing = "[i18n]\ndefault_locale = \"fr\"\n";
        assert_eq!(ensure_i18n_config_block(existing), existing);
    }

    #[test]
    fn i18n_auto_is_inserted_before_the_routes_call() {
        let main_rs = "fn main() {\n    autumn_web::app()\n        .routes(routes![index])\n        .run();\n}\n";
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected an anchor");
        };
        assert!(
            out.contains("        .i18n_auto()\n        .routes(routes![index])"),
            "{out}"
        );
        assert_eq!(
            ensure_i18n_auto(&out),
            I18nAutoWiring::Wired(out.clone()),
            "must be idempotent"
        );
    }

    /// An app that builds its own `Bundle` keeps it — but the caller has to be
    /// told, because the keys written to disk will never reach it.
    #[test]
    fn i18n_auto_reports_a_hand_installed_bundle_rather_than_claiming_success() {
        let main_rs = "fn main() {\n    autumn_web::app()\n        .i18n(my_bundle())\n        .routes(routes![index]);\n}\n";
        assert_eq!(ensure_i18n_auto(main_rs), I18nAutoWiring::CustomBundle);
    }

    /// `autumn new`'s own template mentions `.routes(routes![...])` in a comment
    /// above `fn main`. Anchoring there would write `.i18n_auto()` INTO that
    /// comment: the app compiles, starts, and renders raw keys forever, and the
    /// idempotency guard makes every later run a no-op.
    #[test]
    fn i18n_auto_ignores_a_routes_call_inside_a_comment() {
        let main_rs = concat!(
            "// Register new endpoints by adding them to the .routes(routes![...]) list.\n",
            "fn main() {\n",
            "    autumn_web::app()\n",
            "        .routes(routes![index])\n",
            "        .run();\n",
            "}\n",
        );
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected the real anchor to be found");
        };
        assert!(
            out.contains("        .i18n_auto()\n        .routes(routes![index])"),
            "must anchor on the real builder call:\n{out}"
        );
        assert!(
            out.lines().next().unwrap().ends_with("list."),
            "the comment must be left alone:\n{out}"
        );
    }

    /// A `.i18n_auto()` that appears only in a doc comment must not be mistaken
    /// for a bundle the app already installs.
    #[test]
    fn i18n_auto_ignores_a_mention_inside_a_doc_comment() {
        let main_rs = concat!(
            "/// Call `.i18n_auto()` to load translations.\n",
            "fn main() {\n",
            "    autumn_web::app()\n",
            "        .routes(routes![index]);\n",
            "}\n",
        );
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected an anchor");
        };
        assert!(
            out.contains("        .i18n_auto()\n        .routes(routes![index])"),
            "{out}"
        );
    }

    /// A `main.rs` can hold more than one builder. Wiring the wrong one is
    /// silent — the production app gets no bundle and renders raw keys, and the
    /// idempotency guard stops any later run from correcting it.
    #[test]
    fn i18n_auto_targets_the_builder_the_binary_runs() {
        let main_rs = concat!(
            "fn preview_app() -> App {\n",
            "    autumn_web::app()\n",
            "        .routes(routes![preview])\n",
            "}\n",
            "\n",
            "#[autumn_web::main]\n",
            "async fn main() {\n",
            "    autumn_web::app()\n",
            "        .routes(routes![index])\n",
            "        .run()\n",
            "        .await;\n",
            "}\n",
        );
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected an anchor");
        };
        assert!(
            out.contains(".i18n_auto()\n        .routes(routes![index])"),
            "must wire the builder `main` runs:\n{out}"
        );
        assert!(
            !out.contains(".i18n_auto()\n        .routes(routes![preview])"),
            "must not wire the preview builder:\n{out}"
        );
    }

    /// The common `fn main` -> `build_app()` shape has its builder BEFORE
    /// `fn main`; with only one candidate there is nothing to disambiguate.
    #[test]
    fn i18n_auto_falls_back_to_the_only_builder_when_it_precedes_main() {
        let main_rs = concat!(
            "fn build_app() -> App {\n",
            "    autumn_web::app()\n",
            "        .routes(routes![index])\n",
            "}\n",
            "\n",
            "#[autumn_web::main]\n",
            "async fn main() {\n",
            "    build_app().run().await;\n",
            "}\n",
        );
        let I18nAutoWiring::Wired(out) = ensure_i18n_auto(main_rs) else {
            panic!("expected an anchor");
        };
        assert!(out.contains(".i18n_auto()"), "{out}");
    }

    #[test]
    fn locales_are_embedded_for_embed_builds() {
        // `.i18n_auto()` loads from DISK; an `--embed` build is meant to be
        // self-contained, and the release image ships no sidecar for it.
        let main_rs = concat!(
            "static EMBEDDED_STATIC: autumn_web::include_dir::Dir = autumn_web::embed_static!();\n",
            "fn main() {\n",
            "    let app = app.embedded_static(&EMBEDDED_STATIC);\n",
            "}\n",
        );
        let out = ensure_embedded_locales(main_rs, "i18n").expect("anchors present");
        assert!(out.contains("static EMBEDDED_LOCALES"), "{out}");
        assert!(out.contains("autumn_web::embed_locales!()"), "{out}");
        assert!(
            out.contains("app.embedded_locales(&EMBEDDED_LOCALES)"),
            "{out}"
        );
        assert_eq!(
            out.matches("#[cfg(feature = \"embed-assets\")]").count(),
            2,
            "both edits stay behind the feature the template already gates on:\n{out}"
        );
        // Idempotent, and a configured directory reaches the macro.
        assert_eq!(
            ensure_embedded_locales(&out, "i18n").as_deref(),
            Some(out.as_str())
        );
        let custom = ensure_embedded_locales(main_rs, "translations").unwrap();
        assert!(
            custom.contains("embed_locales!(\"translations\")"),
            "{custom}"
        );
        // An `--api` or hand-rolled `main.rs` has no anchors: reported, not guessed at.
        assert_eq!(ensure_embedded_locales("fn main() {}\n", "i18n"), None);
    }

    #[test]
    fn i18n_auto_reports_no_anchor_rather_than_guessing() {
        let main_rs = "fn main() {\n    println!(\"no builder here\");\n}\n";
        assert_eq!(ensure_i18n_auto(main_rs), I18nAutoWiring::NoAnchor);
    }

    #[test]
    fn config_block_detects_a_spaced_section_header() {
        // `[ i18n ]` is legal TOML; appending a second `[i18n]` beside it makes
        // the whole file unparseable and takes the app's config down with it.
        let existing = "[ i18n ]\ndefault_locale = \"fr\"\n";
        assert_eq!(ensure_i18n_config_block(existing), existing);
    }

    #[test]
    fn the_configured_locale_and_directory_are_read_from_the_config() {
        let (locale, dir) = configured_i18n("[i18n]\ndefault_locale = \"fr\"\n");
        assert_eq!(locale.as_deref(), Some("fr"));
        assert_eq!(dir, None);
        // Spacing and trailing comments are both legal TOML.
        let (locale, dir) = configured_i18n(
            "[ i18n ] # locale settings\ndefault_locale = 'pt-BR' # ours\ndir = \"translations\"\n",
        );
        assert_eq!(locale.as_deref(), Some("pt-BR"));
        assert_eq!(dir.as_deref(), Some("translations"));
        // `#` is an ordinary character inside a quoted value.
        let (_, dir) = configured_i18n("[i18n]\ndir = \"i18n#v2\"\n");
        assert_eq!(dir.as_deref(), Some("i18n#v2"));
        // Keys under some OTHER section are not ours.
        assert_eq!(
            configured_i18n("[server]\ndefault_locale = \"fr\"\ndir = \"x\"\n"),
            (None, None)
        );
        assert_eq!(configured_i18n("[server]\nport = 3000\n"), (None, None));
    }

    #[test]
    fn profile_overlays_that_repoint_i18n_are_reported() {
        let toml = concat!(
            "[i18n]\ndefault_locale = \"en\"\n\n",
            // Same paths as the base — nothing to say about this one.
            "[profile.staging.i18n]\ndefault_locale = \"en\"\n\n",
            "[profile.prod.i18n]\ndir = \"translations\"\ndefault_locale = \"fr\"\n",
        );
        let out = profile_i18n_overrides(toml, "i18n", "en");
        assert_eq!(
            out,
            vec![("prod".to_owned(), "translations/fr.ftl".to_owned())]
        );
        // An overlay of something else entirely is not an i18n overlay.
        assert!(
            profile_i18n_overrides("[profile.prod.server]\nport = 80\n", "i18n", "en").is_empty()
        );
    }

    #[test]
    fn config_block_detects_the_inline_and_dotted_spellings() {
        // TOML expresses one table three ways, and appending `[i18n]` beside any
        // of them is a duplicate definition that makes the file unparseable —
        // taking the whole application config down with it.
        for existing in [
            "i18n = { default_locale = \"fr\", supported_locales = [\"fr\"] }\n",
            "i18n.default_locale = \"fr\"\n",
            "[i18n]\ndefault_locale = \"fr\"\n",
        ] {
            assert_eq!(
                ensure_i18n_config_block(existing),
                existing,
                "must not append a second definition to: {existing}"
            );
        }
        // A dotted key under some OTHER table is a different key entirely.
        let scoped = "[server]\ni18n.enabled = true\n";
        assert!(ensure_i18n_config_block(scoped).contains("[i18n]"));
    }

    #[test]
    fn the_configured_values_are_read_from_the_inline_and_dotted_spellings() {
        let (locale, dir) =
            configured_i18n("i18n = { default_locale = \"fr\", dir = \"translations\" }\n");
        assert_eq!(locale.as_deref(), Some("fr"));
        assert_eq!(dir.as_deref(), Some("translations"));
        let (locale, dir) = configured_i18n("i18n.default_locale = \"pt-BR\"\ni18n.dir = 'tr'\n");
        assert_eq!(locale.as_deref(), Some("pt-BR"));
        assert_eq!(dir.as_deref(), Some("tr"));
    }

    #[test]
    fn config_block_detects_a_header_with_a_trailing_comment() {
        // `[i18n] # locale settings` is one table, not none — appending a second
        // `[i18n]` beside it makes the file unparseable and takes the whole
        // application config down with it.
        let existing = "[i18n] # locale settings\ndefault_locale = \"fr\"\n";
        assert_eq!(ensure_i18n_config_block(existing), existing);
    }

    #[test]
    fn removal_leaves_hand_authored_keys_on_the_same_prefix_alone() {
        // A `post.email.subject` the application owns is not this generator's
        // to delete just because it starts with the resource's name.
        let generated = merge_en_ftl("", "Post", "post", &keys(&[("post.new", "New Post")]));
        let with_hand_authored = format!("{generated}\n# App copy\npost.email.subject = Welcome\n");
        let out = remove_en_ftl_keys(&with_hand_authored, "Post", "post", &HashSet::new());
        assert!(
            out.contains("post.email.subject = Welcome"),
            "a hand-authored key must survive destroy:\n{out}"
        );
        assert!(!out.contains("post.new"), "{out}");
    }

    /// A key defined ABOVE the generated block must not be redefined inside it.
    ///
    /// `parse_ftl` (`autumn/src/i18n.rs`) inserts each entry into a map in file
    /// order, so the last definition wins outright — a second, generated
    /// definition below a hand-authored one does not merely duplicate it, it
    /// silently replaces the translation with English. Reconciliation reads
    /// only the block, so before this it saw the key as absent and appended it.
    #[test]
    fn regeneration_does_not_redefine_a_key_authored_above_the_block() {
        // Establish a block, then hand-author one of the NEXT run's keys above
        // it — the shape you get when someone translates a string before the
        // generator ever emits it, or hoists it out of the block by hand.
        let generated = merge_en_ftl("", "Post", "post", &keys(&[("post.new", "New Post")]));
        let with_hand_authored = format!("post.field.body = Corps du texte\n\n{generated}");

        let out = merge_en_ftl(
            &with_hand_authored,
            "Post",
            "post",
            &keys(&[("post.new", "New Post"), ("post.field.body", "Body")]),
        );

        assert_eq!(
            out.matches("post.field.body =").count(),
            1,
            "the key must be defined exactly once — a second, later definition \
             wins in `parse_ftl` and would replace the translation:\n{out}"
        );
        assert!(
            out.contains("post.field.body = Corps du texte"),
            "the hand-authored value must survive:\n{out}"
        );
        assert!(
            !out.contains("post.field.body = Body"),
            "the generated English must not be written at all:\n{out}"
        );
    }

    #[test]
    fn removal_takes_a_multi_line_value_with_its_key() {
        // A translator may wrap a value over indented continuation lines. Left
        // behind, they either fail the loader outright — and `.i18n_auto()`
        // turns that into a startup panic — or silently glue onto whichever key
        // precedes them, corrupting an unrelated translation.
        let ftl = concat!(
            "common.show = Show\n",
            "\n",
            "# Comment — generated by `autumn generate scaffold --i18n`.\n",
            "comment.new = New Comment\n",
            "\n",
            "# Post — generated by `autumn generate scaffold --i18n`.\n",
            "post.index.title = Post index\n",
            "    continued here\n",
            "post.new = New Post\n",
        );
        let out = remove_en_ftl_keys(ftl, "Post", "post", &chrome(&["common.show"]));
        assert!(
            !out.contains("continued here"),
            "an orphaned continuation either fails the loader — and `.i18n_auto()` \
             turns that into a startup panic — or silently glues onto the key above \
             it:\n{out}"
        );
        assert!(!out.contains("post."), "{out}");
        // The sibling resource keeps the chrome alive.
        assert!(out.contains("common.show = Show"), "{out}");
        assert!(out.contains("comment.new = New Comment"), "{out}");
    }

    /// Chrome is per-surface, so destroying the only resource that had a Trash
    /// view must take `common.trash`/`restore`/`purge` — and nothing else.
    #[test]
    fn chrome_is_pruned_per_key_not_all_or_nothing() {
        let ftl = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[
                ("common.create", "Create"),
                ("common.save", "Save"),
                ("common.trash", "Trash"),
                ("common.restore", "Restore"),
                ("post.new", "New Post"),
            ]),
        );
        // A plain sibling survives: it uses the CRUD chrome but no trash chrome.
        let out = remove_en_ftl_keys(
            &ftl,
            "Post",
            "post",
            &chrome(&["common.create", "common.save"]),
        );
        assert!(out.contains("common.create = Create"), "{out}");
        assert!(out.contains("common.save = Save"), "{out}");
        assert!(
            !out.contains("common.trash") && !out.contains("common.restore"),
            "chrome nothing references any more fails `--strict`:\n{out}"
        );
        assert!(!out.contains("post.new"), "{out}");
    }

    #[test]
    fn removing_the_last_resource_takes_the_now_unreferenced_chrome_with_it() {
        let ftl = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.new", "New Post")]),
        );
        let out = remove_en_ftl_keys(&ftl, "Post", "post", &HashSet::new());
        assert!(
            !out.contains("common.create"),
            "chrome nothing references any more fails `i18n check --strict`:\n{out}"
        );
        // …but a SIBLING resource keeps it alive.
        let two = merge_en_ftl(
            &ftl,
            "Comment",
            "comment",
            &keys(&[("common.create", "Create"), ("comment.new", "New Comment")]),
        );
        let still = remove_en_ftl_keys(&two, "Post", "post", &chrome(&["common.create"]));
        assert!(still.contains("common.create = Create"), "{still}");
        assert!(still.contains("comment.new = New Comment"), "{still}");
    }

    #[test]
    fn a_regenerated_key_lands_inside_its_own_block() {
        let first = merge_en_ftl("", "Post", "post", &keys(&[("post.new", "New Post")]));
        let second = merge_en_ftl(
            &first,
            "Post",
            "post",
            &keys(&[("post.new", "New Post"), ("post.field.body", "Body")]),
        );
        let header_at = second.find("Post — generated by").expect("header");
        let key_at = second.find("post.field.body").expect("new key");
        assert!(
            key_at > header_at,
            "the new key must sit under the header:\n{second}"
        );
        // …and above the block's closing marker, not stranded past it at EOF.
        let footer_at = second.find("# — end Post —").expect("footer");
        assert!(
            key_at < footer_at,
            "the new key must sit INSIDE the block:\n{second}"
        );
    }

    /// A `.ftl` is a file people edit. A translator who groups keys with a
    /// blank line, or leaves a note beside one, must not move the boundary of
    /// what `destroy` owns — otherwise it strands the keys below the separator
    /// with no call sites, and `autumn i18n check --strict` starts failing on
    /// keys whose owner nobody can find.
    /// A `--force` regeneration that dropped a field or a flag must not leave
    /// the keys for those surfaces behind: nothing references them any more, so
    /// `autumn i18n check --strict` fails on them.
    #[test]
    fn regeneration_prunes_keys_whose_surfaces_are_gone() {
        let before = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[
                ("common.create", "Create"),
                ("post.new", "New Post"),
                ("post.field.body", "Body"),
                ("post.search.title", "Search Posts"),
            ]),
        );
        // A translated value, and a note beside a key that survives.
        let edited = before
            .replace("post.new = New Post", "post.new = Nouvel article")
            .replace(
                "post.field.body = Body\n",
                "# on the edit form\npost.field.body = Body\n",
            );
        let after = merge_en_ftl(
            &edited,
            "Post",
            "post",
            &keys(&[("common.create", "Create"), ("post.new", "New Post")]),
        );
        assert!(!after.contains("post.field.body"), "{after}");
        assert!(!after.contains("post.search.title"), "{after}");
        assert!(
            after.contains("post.new = Nouvel article"),
            "a translated value must survive:\n{after}"
        );
        assert!(
            after.contains("# on the edit form"),
            "a translator's note must survive:\n{after}"
        );
        // Chrome is never pruned from here — a sibling resource writes it too.
        assert!(after.contains("common.create = Create"), "{after}");
        // And it settles: regenerating again changes nothing.
        assert_eq!(
            merge_en_ftl(
                &after,
                "Post",
                "post",
                &keys(&[("common.create", "Create"), ("post.new", "New Post")])
            ),
            after
        );
    }

    /// A Fluent continuation is just indented text and usually carries no `=`.
    /// Keeping one whose key was pruned orphans it — the loader either rejects
    /// the bundle (a startup panic, via `.i18n_auto()`) or glues the text onto
    /// the message above, rewriting an unrelated translation.
    #[test]
    fn regeneration_drops_continuation_lines_with_their_pruned_key() {
        let before = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("post.new", "New Post"), ("post.field.body", "Body")]),
        );
        // A wrapped value with NO `=` in the continuation, and a kept key that
        // also wraps — the first must go, the second must stay whole.
        let edited = before
            .replace(
                "post.field.body = Body\n",
                "post.field.body = Body\n    spilling over onto a second line\n",
            )
            .replace(
                "post.new = New Post\n",
                "post.new = New Post\n    also wrapped\n",
            );
        let after = merge_en_ftl(&edited, "Post", "post", &keys(&[("post.new", "New Post")]));
        assert!(!after.contains("post.field.body"), "{after}");
        assert!(
            !after.contains("spilling over"),
            "the pruned key's continuation must go with it:\n{after}"
        );
        assert!(
            after.contains("also wrapped"),
            "a surviving key keeps its own continuation:\n{after}"
        );
    }

    #[test]
    fn an_existing_embed_is_repointed_when_the_bundle_directory_changes() {
        let main_rs = concat!(
            "static EMBEDDED_STATIC: autumn_web::include_dir::Dir = autumn_web::embed_static!();\n",
            "fn main() {\n",
            "    let app = app.embedded_static(&EMBEDDED_STATIC);\n",
            "}\n",
        );
        let embedded = ensure_embedded_locales(main_rs, "i18n").expect("anchors present");
        // The project later moves its bundles; the embed has to follow, or an
        // `--embed` build ships a directory the app no longer reads.
        let moved = ensure_embedded_locales(&embedded, "translations").expect("already embedded");
        assert!(
            moved.contains("embed_locales!(\"translations\")"),
            "{moved}"
        );
        assert!(!moved.contains("embed_locales!()"), "{moved}");
        assert_eq!(
            moved.matches("EMBEDDED_LOCALES").count(),
            2,
            "repointing must not duplicate the wiring:\n{moved}"
        );
        // …and moving back works too, without stacking arguments.
        let back = ensure_embedded_locales(&moved, "i18n").expect("already embedded");
        assert!(back.contains("embed_locales!()"), "{back}");
        assert!(!back.contains("translations"), "{back}");
    }

    #[test]
    fn a_comment_or_blank_line_inside_a_block_does_not_truncate_it() {
        let ftl = merge_en_ftl(
            "",
            "Post",
            "post",
            &keys(&[("post.new", "New Post"), ("post.index.title", "Post index")]),
        );
        let edited = ftl.replace(
            "post.index.title = Post index\n",
            "\n# careful: this one is on a button\npost.index.title = Post index\n",
        );
        assert_ne!(edited, ftl, "fixture must actually insert the separator");
        let out = remove_en_ftl_keys(&edited, "Post", "post", &HashSet::new());
        assert!(
            !out.contains("post.index.title"),
            "a key below the separator is still the generator's:\n{out}"
        );
        assert!(!out.contains("post.new"), "{out}");
        assert!(!out.contains("# — end Post —"), "{out}");
    }

    /// A bundle written before blocks carried closing markers still merges and
    /// destroys correctly — the boundary falls back to the first blank line or
    /// foreign comment.
    #[test]
    fn a_block_without_a_closing_marker_still_round_trips() {
        let legacy = concat!(
            "# Post — generated by `autumn generate scaffold --i18n`.\n",
            "post.new = New Post\n",
            "\n",
            "# App copy\n",
            "post.email.subject = Welcome\n",
        );
        let out = remove_en_ftl_keys(legacy, "Post", "post", &chrome(&["common.create"]));
        assert!(!out.contains("post.new"), "{out}");
        assert!(out.contains("post.email.subject = Welcome"), "{out}");
    }

    /// A `dir` that moved since an earlier run leaves that run's `COPY` pair
    /// behind. `COPY` fails the build when its source is gone from the context,
    /// so this has to be surfaced rather than quietly doubled up.
    #[test]
    fn a_moved_locale_dir_is_reported_against_the_dockerfile() {
        let dockerfile = concat!(
            "FROM rust AS builder\n",
            "COPY migrations ./migrations\n",
            "COPY i18n ./i18n\n",
            "\n",
            "FROM debian AS runtime\n",
            "COPY --from=builder /app/migrations /app/migrations\n",
            "COPY --from=builder /app/i18n /app/i18n\n",
        );
        assert_eq!(
            stale_dockerfile_i18n_dir(dockerfile, "translations").as_deref(),
            Some("i18n")
        );
        // The configured directory is not stale, and neither is a Dockerfile
        // this generator has never touched.
        assert_eq!(stale_dockerfile_i18n_dir(dockerfile, "i18n"), None);
        assert_eq!(
            stale_dockerfile_i18n_dir(
                "FROM rust AS builder\nCOPY migrations ./migrations\n",
                "i18n"
            ),
            None
        );
    }

    /// The shape it matches (`COPY <x> ./<x>`) is also an ordinary asset copy,
    /// so agreement across BOTH stages is what promotes it from coincidence —
    /// and even then the caller only warns.
    #[test]
    fn an_unrelated_copy_in_one_stage_is_not_read_as_a_moved_bundle() {
        let dockerfile = concat!(
            "FROM rust AS builder\n",
            "COPY migrations ./migrations\n",
            "COPY static ./static\n",
            "\n",
            "FROM debian AS runtime\n",
            "COPY --from=builder /app/migrations /app/migrations\n",
            "COPY --from=builder /app/assets /app/assets\n",
        );
        assert_eq!(stale_dockerfile_i18n_dir(dockerfile, "i18n"), None);
    }

    /// A comma inside a quoted value belongs to the value. Split through it and
    /// `toml_scalar_value` sees an unterminated string and discards it, so the
    /// generator falls back to `i18n/` and writes where the runtime never looks.
    #[test]
    fn an_inline_table_splits_on_separators_not_on_commas_in_values() {
        let toml = r#"i18n = { dir = "translations,v2", default_locale = "fr" }"#;
        assert_eq!(
            configured_i18n(toml),
            (Some("fr".to_owned()), Some("translations,v2".to_owned()))
        );
        // An escaped quote inside a basic string does not end it.
        let escaped = r#"i18n = { dir = "od\"d", default_locale = "fr" }"#;
        assert_eq!(configured_i18n(escaped).1.as_deref(), Some(r#"od"d"#));
    }

    /// `dir` is the one config value that becomes Rust SOURCE, and TOML happily
    /// carries characters Rust's lexer reads as escapes.
    #[test]
    fn the_embedded_locale_dir_is_escaped_as_a_rust_literal() {
        let main_rs = concat!(
            "static EMBEDDED_STATIC: autumn_web::include_dir::Dir = autumn_web::embed_static!();\n",
            "    let app = app.embedded_static(&EMBEDDED_STATIC);\n",
        );
        let out = ensure_embedded_locales(main_rs, r"translations\bundles").expect("anchors");
        assert!(
            out.contains(r#"embed_locales!("translations\\bundles")"#),
            "a backslash must reach Rust as an escaped backslash, not as `\\b`:\n{out}"
        );
        let quoted = ensure_embedded_locales(main_rs, r#"od"d"#).expect("anchors");
        assert!(
            quoted.contains(r#"embed_locales!("od\"d")"#),
            "a quote must not terminate the literal:\n{quoted}"
        );
    }

    #[test]
    fn toml_values_are_decoded_before_they_become_paths() {
        // A basic string processes escapes; the app's loader reads the DECODED
        // value, so the generator has to write to the same place.
        assert_eq!(
            toml_scalar_value(r#" "fr" "#).as_deref(),
            Some("fr"),
            "a `\\u` escape must resolve"
        );
        assert_eq!(
            toml_scalar_value(r#" "i18n\\bundles" "#).as_deref(),
            Some(r"i18n\bundles"),
            "an escaped backslash is one backslash"
        );
        // A literal string does NOT process escapes, by TOML's definition.
        assert_eq!(
            toml_scalar_value(r" 'i18n\\bundles' ").as_deref(),
            Some(r"i18n\\bundles")
        );
        // An unknown escape survives rather than failing generation.
        assert_eq!(toml_scalar_value(r#" "a\qb" "#).as_deref(), Some(r"a\qb"));
        assert_eq!(toml_scalar_value(r#" "plain" "#).as_deref(), Some("plain"));
    }

    #[test]
    fn dockerfile_gains_the_bundle_in_both_stages() {
        let dockerfile = concat!(
            "FROM rust AS builder\n",
            "COPY migrations ./migrations\n",
            "\n",
            "FROM debian AS runtime\n",
            "COPY --from=builder /app/migrations /app/migrations\n",
        );
        let out = ensure_dockerfile_i18n_copy(dockerfile, "i18n").expect("anchors present");
        assert!(out.contains("COPY i18n ./i18n"), "{out}");
        assert!(
            out.contains("COPY --from=builder /app/i18n /app/i18n"),
            "{out}"
        );
        assert_eq!(
            ensure_dockerfile_i18n_copy(&out, "i18n").as_deref(),
            Some(out.as_str()),
            "must be idempotent"
        );
        // A Dockerfile with no anchor is reported, not guessed at.
        assert_eq!(ensure_dockerfile_i18n_copy("FROM scratch\n", "i18n"), None);
    }
}
