mod a11y_verify;
mod api_scaffold;
mod cloud_native_scaffold;
mod db;
mod db_pull;
mod deploy;
mod generate_references_postgres;
mod generate_tauri_mobile;
mod generate_tauri_mobile_offline;
mod i18n_check;
mod lifecycle_check;
mod manifest_posture;
mod migrate_down;
mod offsite_backup;
mod repo_hygiene;
mod scaffold_belongs_to;
mod scaffold_form_for;
mod scaffold_search;
mod scaffold_sort_filter;
mod scaffold_validation;
mod schema_migrate;
#[cfg(feature = "sqlite")]
mod schema_migrate_sqlite;
mod seed_model_linking;
#[cfg(unix)]
mod serve;
mod tauri_mobile_thin_client;
mod test_command;
mod webhook_sim;
